# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f408f62289664ddebde26ba0baf865ecb6002f82674b63858d3eef89c2bb3e7e4b67008b2315a86a2d2db885a56ba281bc9f2c0fb1f417e4761255131e07a9

test:
  secret_key_base: 4db77530f5237a7735af6aa420cfb6128a06445174d06082e12eedb481957574c8212db776f44080ef1d12cec60118a2aefd00df48d01722fa3556fe36a8875c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 38f408f62289664ddebde26ba0baf865ecb6002f82674b63858d3eef89c2bb3e7e4b67008b2315a86a2d2db885a56ba281bc9f2c0fb1f417e4761255131e07a9

