# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

unless User.exists?
  User.create!({:email => "jmarzin@gmail.com", :admin => true, :password => "51julie2", :password_confirmation => "51julie2" })
end

liste = [
    [1,"L'individu"],
    [2,"La famille"],
    [3,"Le corps"],
    [4,"Les sentiments et les émotions"],
    [5,"La maison"],
    [6,"La cuisine et les repas"],
    [7,"La ville"],
    [8,"Les courses"],
    [9,"L'éducation"],
    [10,"Le travail"],
    [11,"La santé"],
    [12,"Les voyages et les sorties"],
    [13,"Les arts et les loisirs"],
    [14,"Les sports"],
    [15,"Le temps qu'il fait, le temps qui passe"],
    [16,"La nature et l'environnement"],
    [17,"Les médias"],
    [18,"Les techniques de communication"],
    [19,"La vie en société"],
    [20,"La politique"],
    [21,"Pensée, opinion, croyance"],
    [22,"Du français à l'italien"]]

liste.each do |c|
  @c = Category.find_by(numero: c[0])
  if @c
    @c.description = c[1]
    @c.save!
  else
    @c = Category.create(numero: c[0], description: c[1])
  end
end

liste = [
    [22,"à","à midi",8,"a mezzogiorno"],
    [22,"à","au dix-neuvième siècle",8,"nel diciannovésimo sécolo"],
    [22,"à","au lit",8,"a letto"],
    [22,"à","au hasard",8,"a caso"],
    [22,"à","au théâtre",8,"a teatro"],
    [22,"à","au contact de",8,"a contatto con"],
    [22,"à","ces chaussures sont à elle",8,"queste scarpe sono sue"],
    [22,"à","au printemps",8,"in primavera"],
    [22,"à","à la montagne",8,"in montagna"],
    [22,"à","à l'heure",8,"in oràrio"],
    [22,"à","à la bibliothèque",8,"in biblioteca"],
    [22,"à","à la piscine",8,"in piscina"],
    [22,"à","à la campagne",8,"in campagna"],
    [22,"à","à la banque",8,"in banca"],
    [22,"à","j'ai beaucoup de choses à faire",8,"ho molte cose da fare"],
    [22,"à","qui est cette fille aux yeux bleus ?",8,"chi è la ragazza con gli occhi azzurri?"],
    [22,"à","ces gants sont à lui",8,"questi guanti sono suoi"],
    [22,"à","à l'école",8,"a scuola"],
    [22,"à","à qui est-ce ?",8,"di chi è?"],
    [22,"à","à la messe",8,"a messa"],
    [22,"à","à 5 heures",8,"alle cinque"],
    [22,"à","à minuit",8,"a mezzanotte"],
    [22,"à","à la différence de",8,"a differenza di"],
    [22,"à","à la télé",8,"in tivù"],
    [22,"à","au bureau",8,"in uffìcio"],
    [22,"à","à la maison",8,"a casa"],
    [22,"à","une tasse à café",8,"una tazzina da caffè"],
    [22,"à","ce livre est à Giani",8,"questo libro è di Giani"],
    [7,"abribus","un abribus",8,"una pensilina"],
    [6,"abricot","un abricot",8,"un'albicocca"],
    [22,"accident","un accident de la route",8,"un incidente/un incidente stradale"],
    [22,"accident","un accident du travail",8,"un infortùnio sul lavoro/un infortùnio"],
    [22,"accident","les accidents de la vie",8,"i casi della vita"],
    [2,"accouchement","un accouchement",8,"un parto"],
    [2,"accoucher","accoucher",8,"partorire"],
    [5,"accueillant","accueillant",8,"accogliente"],
    [5,"acheter","acheter",8,"comprare"],
    [5,"acier","un acier",8,"un acciàio"],
    [5,"acompte","un acompte",8,"un acconto"],
    [2,"adolescence","une adolescence",8,"un'adolescenza"],
    [1,"adresse","une adresse (postale)",8,"un indirizzo"],
    [22,"adresser","nous adressons nos compliments au vainqueur",8,"rivolgiamo i nostri complimenti al vincitore"],
    [22,"adresser","Veuillez adresser ce colis à l'adresse suivante...",8,"La prego di spedire questo pacco all'indirizzo seguente..."],
    [22,"adresser","à qui faut-il adresser cette lettre ?",8,"a chi va indirizzata questa léttera?"],
    [22,"adresser","nous vous adressons nos meilleurs voeux",8,"vi mandiamo i nostri migliori auguri"],
    [22,"adresser","il ne m'a plus adressé la parole",8,"non mi ha più rivolto la parola"],
    [22,"adresser","addressez-vous à l'office du tourisme",8,"rivolgétevi all'uffìcio del turismo"],
    [22,"adresser","l'acteur s'est directement adressé au public",8,"l'attore si è direttamente rivolto al pùbblico"],
    [4,"affection","une affection",8,"un affetto"],
    [4,"affectueux","affectueux",8,"affettuoso"],
    [6,"affiné","affiné",8,"stagionato"],
    [4,"affligé","affligé",8,"afflitto"],
    [2,"âge","un âge adulte",8,"un'età adulta"],
    [1,"âge","un âge (état civil)",8,"un'età"],
    [2,"âgée","une personne âgée",8,"una persona anziana"],
    [5,"agence","une agence immobilière",8,"un'agenzia immobiliare"],
    [9,"agenda","un agenda/un cahier de textes",8,"un diàrio"],
    [4,"agité","agité",8,"agitato"],
    [6,"agneau","un agneau",8,"un agnello"],
    [1,"agréable","agréable",8,"gradévole"],
    [6,"agrume","les agrumes",8,"gli agrumi"],
    [6,"ail","un ail",8,"un àglio"],
    [4,"aimer","aimer",8,"amare"],
    [4,"aimer","aimer (un ami)",8,"voler bene a"],
    [3,"allonger","s'allonger",8,"sdraiarsi"],
    [5,"aménager","aménager",8,"sistemare"],
    [4,"ami","le meilleur ami",8,"l'amico del cuore"],
    [2,"ami","un petit ami",8,"un ragazzo"],
    [2,"amie","une petite amie",8,"una ragazza"],
    [4,"amitié","une amitié",8,"un'amicìzia"],
    [4,"amour","un amour",8,"un amore"],
    [4,"amoureux","amoureux",8,"innamorato"],
    [5,"ampoule","une ampoule (éclairage)",8,"una lampadina"],
    [1,"amusant","amusant",8,"divertente"],
    [5,"angle","un angle",8,"un àngolo"],
    [4,"angoisse","une angoisse/une anxiété",8,"un'angòscia/un'ànsia"],
    [4,"angoissé","angoissé",8,"ansioso"],
    [7,"animé","animé",8,"animato"],
    [2,"anniversaire","un anniversaire",8,"un compleanno"],
    [2,"anniversaire","fêter son anniversaire",8,"còmpiere gli anni"],
    [5,"annonce","une annonce immobilière",8,"un annùncio immobiliare"],
    [1,"antipathique","antipathique",8,"antipàtico"],
    [5,"appartement","un appartement",8,"un appartamento"],
    [1,"appeler","s'appeler",8,"chiamarsi"],
    [9,"apprendre","apprendre",8,"imparare"],
    [5,"armoire","une armoire/un placard",8,"un armàdio"],
    [5,"arrhes","les arrhes",8,"la caparra"],
    [6,"artichaud","un artichaud",8,"un carciofo"],
    [2,"asseoir","s'asseoir",8,"sedersi"],
    [4,"assez","en avoir assez",8,"stufarsi"],
    [6,"assiette","une assiette creuse",8,"un piatto fondo"],
    [6,"assiette","une assiette",8,"un piatto"],
    [7,"attendre","attendre son tour",8,"aspettare il pròprio turno"],
    [9,"attentif","attentif",8,"attento"],
    [4,"attristé","attristé",8,"rattristato"],
    [6,"aubergine","une aubergine",8,"una melanzana"],
    [9,"baccalauréat","le baccalauréat",8,"la maturità"],
    [5,"baignoire","une baignoire",8,"una vasca"],
    [4,"baiser","un baiser",8,"un bàccio"],
    [7,"balançoire","une balançoire",8,"un'altalena"],
    [9,"banc","un banc (école)",8,"un banco"],
    [7,"banc","un banc (public)",8,"una panchina"],
    [7,"banlieue","une banlieue",8,"una periferia"],
    [7,"banque","une banque",8,"una banca"],
    [6,"bar","un bar/un loup",8,"una spìgola"],
    [1,"barbe","une barbe",8,"una barba"],
    [5,"bariolé","bariolé/bigarré",8,"variopinto"],
    [8,"bas","les bas",8,"le calze"],
    [6,"basilic","un basilic",8,"un basìlico"],
    [9,"bavard","bavard",8,"chiacchierone"],
    [1,"beau","beau",8,"bello"],
    [2,"beau-frère","un beau-frère",8,"un cognato"],
    [2,"beau-père","le beau-père (père du conjoint)",8,"il suòcero"],
    [2,"beau-père","un beau-père (conjoint de la mère)",8,"un patrigno"],
    [2,"beaux-parents","les beaux-parents",8,"i suòceri"],
    [2,"belle-mère","une belle-mère (conjoint du père)",8,"una matrigna"],
    [2,"belle-mère","la belle-mère (mère du conjoint)",8,"la suòcera"],
    [2,"belle-soeur","une belle-soeur",8,"una cognata"],
    [6,"beurre","le beurre",8,"il burro"],
    [5,"bibliothèque","une bibliothèque (meuble)",8,"una libreria"],
    [5,"blanc","blanc",8,"bianco"],
    [4,"blessé","blessé",8,"ferito"],
    [5,"bleu","bleu ciel",8,"celeste"],
    [5,"bleu","bleu",8,"blu"],
    [1,"blond","blond",8,"biondo"],
    [6,"boeuf","le boeuf (viande)",8,"il manzo"],
    [5,"bois","le bois",8,"il legno"],
    [7,"boîte","une boîte aux lettres (dans la rue)",8,"una buca delle léttere"],
    [6,"bol","un bol",8,"una scodella"],
    [4,"bonheur","un bonheur",8,"una felicità"],
    [5,"bord","un bord",8,"un bordo"],
    [8,"botte","une botte",8,"una stivale"],
    [3,"bouche","une bouche",8,"una bocca"],
    [8,"boucherie","une boucherie",8,"una macelleria"],
    [6,"bouillir","bouillir",8,"bollire"],
    [8,"boulangerie","une boulangerie",8,"una panetteria/il forno"],
    [7,"boulevard","un boulevard",8,"un viale"],
    [7,"boulevard","un boulevard/une avenue",8,"un corso"],
    [4,"bouleversant","bouleversant",8,"sconvolgente"],
    [6,"bouquet","le bouquet garni",8,"gli odori"],
    [6,"bouquet","un bouquet/une botte",8,"un mazzo"],
    [9,"bourse","une bourse (école)",8,"una borsa di stùdio"],
    [3,"bras","un bras, les bras",8,"un bràccio, le bràccia"],
    [6,"brebis","de brebis",8,"di pécora/pecorino"],
    [3,"brosse","une brosse à dents",8,"uno spazzolino da denti"],
    [3,"brosse","la brosse (à cheveux)",8,"la spàzzola"],
    [2,"bru","une bru",8,"una nuora"],
    [6,"brûlé","brûlé",8,"bruciato"],
    [1,"brun","brun",8,"moro"],
    [7,"bruyant","bruyant",8,"rumoroso"],
    [5,"buanderie","une buanderie",8,"una lavanderia"],
    [6,"bufflonne","de bufflonne",8,"di bùfala"],
    [9,"bulletin","un bulletin scolaire",8,"una pagella"],
    [9,"bureau","un bureau (de l'enseignant)",8,"una càttedra"],
    [7,"bureau","un bureau de poste",8,"un uffìcio postale"],
    [5,"bureau","un bureau (meuble)",8,"una scrivania"],
    [5,"bureau","un bureau (pièce)",8,"uno stùdio"],
    [6,"cabillaud","un cabillot/une morue",8,"un merluzzo"],
    [8,"caddie","un caddie",8,"un carrello"],
    [9,"cahier","un cahier",8,"un quaderno"],
    [8,"caleçon","le caleçon",8,"i boxer"],
    [1,"calme","calme",8,"calmo"],
    [5,"canapé","un canapé",8,"un divano"],
    [6,"canard","un canard",8,"un'ànatra"],
    [9,"cancre","un cancre",8,"un somaro"],
    [1,"caractère","un caractère",8,"un caràttere"],
    [6,"carotte","une carotte",8,"una carota"],
    [5,"carré","carré",8,"quadrato"],
    [9,"cartable","un cartable/un dossier",8,"una cartella"],
    [1,"carte","une carte d'identité",8,"una carta d'identità"],
    [6,"casserole","une casserolle/une marmite",8,"una péntola"],
    [5,"cave","une cave",8,"una cantina"],
    [8,"ceinture","une ceinture",8,"una cinta/una cintura"],
    [6,"céleri","le céleri",8,"il sédano"],
    [1,"célibataire","une célibataire",8,"una single/una nùbile"],
    [1,"célibataire","un célibataire",8,"un single/un célibe"],
    [8,"centre","un centre commercial",8,"un centro commerciale"],
    [7,"centre","un centre historique",8,"un centro stòrico"],
    [7,"centre","un centre-ville",8,"un centro"],
    [6,"céréales","les céréales",8,"i cereali"],
    [5,"chaise","une chaise",8,"una sédia"],
    [5,"chambre","une chambre à coucher",8,"una càmera da letto"],
    [6,"champignon","un champignon",8,"un fungo"],
    [8,"changer","se changer",8,"cambiarsi"],
    [8,"chapeau","un chapeau",8,"un cappello"],
    [6,"charcuterie","la charcuterie",8,"i salumi"],
    [1,"châtain","châtain",8,"castano"],
    [6,"chaud","chaud",8,"caldo"],
    [5," chaudière","une chaudière",8,"una caldàia"],
    [5,"chauffage","un chauffage",8,"un riscaldamento"],
    [8,"chaussettes","les chaussettes",8,"i calzini"],
    [8,"chaussure","une chaussure",8,"una scarpa"],
    [1,"chauve","chauve",8,"calvo/pelato"],
    [5,"cheminée","une cheminée",8,"un caminetto"],
    [8,"chemise","une chemise",8,"una camìcia"],
    [8,"chemise","une chemise de nuit",8,"una vestàglia"],
    [9,"chercheur","un chercheur",8,"un ricercatore"],
    [1,"cheveux","les cheveux",8,"i capelli"],
    [3,"cheville","une cheville",8,"una cavìglia"],
    [6,"chèvre","de chèvre",8,"di capra/caprino"],
    [4,"choquant","choquant",8,"scioccante"],
    [6,"chou","un chou",8,"un càvolo"],
    [5,"ciment","le ciment",8,"un cemento"],
    [7,"cimetière","un cimetière",8,"un cimitero/un composanto"],
    [6,"citron","un citron",8,"un limone"],
    [1,"clair","clair",8,"claro"],
    [7,"clocher","un clocher",8,"un campanile"],
    [7,"cloître","un cloître",8,"un chiostro"],
    [3,"coiffer","se coiffer",8,"pettinarsi"],
    [4,"colère","s'énerver/se mettre en colère",8,"arrabbiarsi"],
    [4,"colère","une colère",8,"una còllera"],
    [1,"colérique","colérique",8,"collérico"],
    [9,"collège","le collège",8,"le médie"],
    [9,"collège","être au collège",8,"fare le médie"],
    [5,"colocataire","un colocataire",8,"un coinquilino"],
    [5,"coloré","coloré",8,"colorato"],
    [2,"compagne","une compagne",8,"una compagna"],
    [2,"compagnon","un compagnon",8,"un compagno"],
    [1,"comporter","se comporter",8,"comportarsi"],
    [5,"confortable","confortable",8,"còmodo"],
    [5,"congélateur","un congélateur",8,"un congelatore"],
    [6,"congelé","congelé",8,"congelato"],
    [4,"content","content",8,"contento"],
    [5,"contrat","un contrat",8,"un contratto"],
    [1,"coordonnée","les coordonnées (état civil)",8,"i recàpiti"],
    [5,"copropriété","une copropriété",8,"un condomìnio"],
    [6,"coquillage","un coquillage",8,"una conchìglia"],
    [6,"coquille","une coquille Saint-Jacques",8,"una capasanta"],
    [9,"corriger","corriger",8,"corréggere"],
    [1,"costaud","costaud",8,"robusto"],
    [8,"costume","un costume",8,"un completo"],
    [3,"cou","le cou",8,"il collo"],
    [3,"coude","un coude",8,"un gòmito"],
    [4,"coup","le coup de foudre",8,"il colpo di fùlmine"],
    [6,"couper","couper",8,"tagliare"],
    [6,"courgette","une courgette",8,"una zucchina"],
    [3,"courir","courir",8,"còrrere"],
    [9,"cours","un cours (ensemble des leçons)",8,"un corso"],
    [9,"cours","une salle de cours",8,"un'àula"],
    [9,"cours","un cours (la leçon)",8,"una lezione"],
    [8,"courses","faire les courses",8,"fare la spesa"],
    [1,"court","court",8,"corto"],
    [2,"cousin","un cousin",8,"un cugino"],
    [2,"cousine","une cousine",8,"una cugina"],
    [5,"coussin","un coussin/un oreiller",8,"un cuscino"],
    [6,"couteau","un couteau",8,"un coltello"],
    [6,"couvercle","un couvercle",8,"un copérchio"],
    [6,"couverts","les couverts",8,"le posate"],
    [5,"couverture","une couverture",8,"una coperta"],
    [6,"crabe","un crabe",8,"un grànchio"],
    [9,"craie","une craie",8,"un gesso"],
    [4,"craindre","craindre",8,"temere"],
    [3,"crayon","un crayon",8,"una matita"],
    [9,"crèche","une crèche",8,"un asilo nido"],
    [3,"crème","une crème",8,"una crema"],
    [6,"crevette","une crevette",8,"un gamberetto"],
    [7,"croisement","un croisement",8,"un incròcio"],
    [2,"croissance","la croissance",8,"la créscita"],
    [6,"cru","cru",8,"crudo"],
    [6,"cuillère","une cuillère",8,"un cucchiàio"],
    [6,"cuillère","une petite cuillère",8,"un cucchiaino"],
    [6,"cuire","cuire",8,"cuòcere"],
    [5,"cuisine","la cuisine (pièce)",8,"la cucina"],
    [6,"cuisiner","cuisiner",8,"cucinare"],
    [3,"cuisse","une cuisse",8,"una còscia"],
    [6,"cuit","cuit",8,"cotto"],
    [7,"cul-de-sac","un cul-de-sac",8,"un vìcolo cieco"],
    [8,"culotte","la culotte",8,"le mutande"],
    [6,"cumin","un cumin",8,"un cumino"],
    [5,"cuvette","une cuvette",8,"una tazza"],
    [6,"débarasser","débarasser (la table)",8,"sparecchiare"],
    [5,"débarras","un débarras/un cagibi",8,"uno sgabuzzino"],
    [8,"débraillé","débraillé",8,"sbracato"],
    [1,"défaut","un défaut",8,"un difetto"],
    [6,"déjeuner","déjeuner (verbe)",8,"pranzare"],
    [5,"déménager","déménager",8,"traslocare"],
    [2,"demi-frère","un demi-frère",8,"un fratellastro"],
    [2,"demi-soeur","une demi-soeur",8,"una sorellastra"],
    [8,"démodé","démodé",8,"fuori moda"],
    [3,"dentifrice","un dentifrice",8,"un dentifrìcio"],
    [8,"dépenser","dépenser",8,"spéndere"],
    [1,"dépensier","dépensier",8,"spendaccione"],
    [7,"déplacer","se déplacer",8,"spostarsi"],
    [4,"déprimé","déprimé",8,"depresso"],
    [1,"désagréable","désagréable",8,"sgradévole"],
    [4,"désirer","désirer",8,"desiderare"],
    [5,"désordonné","désordonné",8,"disordinato"],
    [7,"desservi","bien desservi",8,"collegato bene"],
    [7,"desservir","desservir (transport)",8,"collegare"],
    [9,"devoir","les devoirs",8,"i còmpiti"],
    [5,"dimension","une dimension/une taille",8,"una dimensione"],
    [6,"dinde","une dinde",8,"un tacchino"],
    [6,"dîner","un dîner",8,"una cena"],
    [6,"dîner","dîner (verbe)",8,"cenare"],
    [9,"diplôme","passer son diplôme universitaire",8,"laurearsi"],
    [9,"diplôme","un diplôme universitaire",8,"una làurea"],
    [9,"diplôme","un diplôme",8,"un diploma"],
    [9,"diplômé","un diplômé",8,"un laureato"],
    [7,"distributeur","un distributeur automatique",8,"un distributore automàtico"],
    [2,"divorce","un divorce",8,"un divòrzio"],
    [1,"divorcé","divorcé",8,"divorziato"],
    [2,"divorcer","divorcer",8,"divorziare"],
    [9,"doctorant","un doctorant",8,"un dottorando"],
    [9,"doctorat","un doctorat",8,"un dottorato"],
    [3,"doigt","un doigt, les doigts",8,"un dito, le dita"],
    [6,"dorade","une daurade",8,"un'orata"],
    [3,"dos","un dos",8,"una schiena"],
    [5,"douche","une douche",8,"una dòccia"],
    [1,"doux","doux",8,"dolce"],
    [5,"drap","un drap, les draps",8,"un lenzuolo, le lenzuola"],
    [5,"droit","droit",8,"dritto"],
    [1,"drôle","drôle",8,"buffo"],
    [5,"dur","dur",8,"duro"],
    [8,"écharpe","une écharpe",8,"una sciarpa"],
    [9,"échouer","échouer (examen)",8,"éssere bocciato"],
    [9,"école","une école",8,"una scuola"],
    [9,"écolier","un écolier",8,"uno scolaro"],
    [3,"écouter","écouter",8,"ascoltare"],
    [6,"écrevisse","une écrevisse",8,"un gàmbero"],
    [9,"éducation","l'éducation nationale",8,"la pùbblica istruzione"],
    [4,"effrayer","effrayer",8,"spaventare"],
    [7,"église","une église",8,"una chiesa"],
    [1,"égoïste","égoïste",8,"egoista"],
    [1,"élancé","élancé",8,"slanciato"],
    [9,"élève","un élève",8,"un alunno"],
    [1,"élevé","bien élevé",8,"educato"],
    [7,"embouteillage","un embouteillage",8,"un ingorgo"],
    [4,"embrasser","embrasser",8,"baciare"],
    [5,"emménager","emménager",8,"trasferirsi"],
    [4,"émouvant","émouvant",8,"commovente"],
    [4,"ému","ému",8,"commosso"],
    [6,"encas","un encas",8,"uno spuntino"],
    [2,"enfance","une enfance",8,"un'infànzia"],
    [2,"enfant","les enfants (parenté)",8,"i figli"],
    [2,"enfant (âge)","l'enfant",8,"il bambino/il bimbo"],
    [8,"enfiler","enfiler",8,"infilare"],
    [4,"enlacer","enlacer",8,"abbracciare"],
    [8,"enlever","enlever",8,"togliere"],
    [1,"ennuyeux","ennuyeux",8,"noioso"],
    [9,"enseignant","un enseignant",8,"un insegnante/un docente"],
    [9,"enseignant","un enseignant titulaire",8,"un insegnante di ruolo"],
    [9,"enseignant","une enseignante",8,"un'insegnante"],
    [9,"enseigner","enseigner",8,"insegnare"],
    [3,"entendre","entendre/sentir",8,"sentire"],
    [4,"entendre","bien s'entendre",8,"andare d'accordo"],
    [2,"enterrement","un enterrement",8,"un funerale"],
    [5,"épaisseur","une épaisseur",8,"uno spessore"],
    [3,"épaule","les épaules",8,"le spalle"],
    [6,"épicé","épicé/piquant",8,"piccante"],
    [8,"épicerie","une épicerie",8,"un alimentari"],
    [6,"épices","les épices",8,"le spézie"],
    [3,"épiler","s'épiler",8,"depilarsi"],
    [3,"épiler","s'épiler à la cire",8,"farsi la ceretta"],
    [6,"épinards","les épinards",8,"gli spinaci"],
    [6,"éplucher","éplucher",8,"pelare/sbucciare"],
    [2,"époux","les époux",8,"i còniugi"],
    [6,"espadon","un espadon",8,"un pescespada"],
    [8,"essayer","essayer",8,"provare"],
    [3,"essuyer","s'essuyer/se sécher",8,"asciugarsi"],
    [5,"étage","un étage",8,"un piano"],
    [5,"étagère","une étagère",8,"una ménsola"],
    [5,"état","un état des lieux",8,"un inventàrio"],
    [8,"étiquette","une étiquette",8,"un'etichetta"],
    [4,"étourdi","étourdi",8,"frastornato"],
    [4,"étreinte","une accolade/une étreinte",8,"un abbràccio"],
    [9,"études","les études universitaires",8,"gli studi universitari"],
    [9,"étudiant","un étudiant de première année",8,"una matrìcola"],
    [9,"étudiant","un étudiant",8,"uno studente"],
    [5,"évier","un évier",8,"un lavello/un lavandino"],
    [9,"examen","un examen (école)",8,"un esame/una prova"],
    [9,"examen","réussir un examen",8,"passare un esame"],
    [9,"exercice","un exercice",8,"un esercìzio"],
    [2,"ex-femme","une ex-femme",8,"un'ex-mòglie"],
    [2,"ex-mari","un ex-mari",8,"un ex-marito"],
    [9,"expulser","expulser",8,"espéllere"],
    [1,"extraverti","extraverti",8,"estroverso"],
    [9,"faculté","une faculté (école)",8,"una facoltà"],
    [6,"fade","fade",8,"insìpido"],
    [4,"faire","faire l'amour",8,"fare l'amore"],
    [2,"famille","la famille monoparentale",8,"la famìglia monoparentale"],
    [6,"farine","une farine",8,"una farina"],
    [5,"fauteuil","un fauteuil",8,"una poltrona"],
    [1,"femme","une femme",8,"una donna"],
    [2,"femme","la femme (épouse)",8,"la mòglie"],
    [5,"fenêtre","une fenêtre",8,"una finestra"],
    [5,"fer","un fer à repasser",8,"un ferro da stiro"],
    [5,"fer","le fer",8,"il ferro"],
    [3,"fesse","les fesses",8,"il sedere"],
    [7,"feu","un feu de circulation",8,"un semàforo"],
    [9,"feuille","une feuille (papier)",8,"un fòglio"],
    [9,"feutre","un feutre (écriture)",8,"un pennarello"],
    [2,"fiancé","un fiancé",8,"un fidanzato"],
    [2,"fiancée","une fiancée",8,"una fidanzata"],
    [2,"fiancer","se fiancer",8,"fidanzarsi"],
    [2,"fille","la fille/l'enfant",8,"la fìglia"],
    [2,"fille","une vieille fille",8,"una zitella"],
    [2,"fils","le fils/l'enfant",8,"il fìglio"],
    [1,"foncé","foncé",8,"scuro"],
    [3,"fond de teint","un fond de teint",8,"un fondotinta"],
    [6,"fondu","fondu",8,"fuso"],
    [7,"fontaine","une fontaine",8,"una fontana"],
    [5,"four","un (four à) microonde",8,"un microonde"],
    [5,"four","un four",8,"un forno"],
    [6,"fourchette","une fourchette",8,"una forchetta"],
    [6,"frais","frais",8,"fresco"],
    [6,"fraise","une fraise",8,"una fràgola"],
    [6,"framboise","une framboise",8,"un lampone"],
    [4,"frayeur","une frayeur",8,"uno spavento"],
    [2,"frère","un frère",8,"un fratello"],
    [5,"frigidaire","un frigidaire",8,"un frigorìfero"],
    [6,"frire","frire",8,"frìggere"],
    [6,"froid","froid",8,"freddo"],
    [6,"fromage","un fromage de brebis à pâte dure",8,"un pecorino"],
    [6,"fromage","un fromage",8,"un formàggio"],
    [6,"fromage","un fromage frais de buflonne",8,"una mozzarella"],
    [6,"fromage","un fromage de vache à pâte fraîche",8,"una ricotta"],
    [6,"fromage","un fromage de vache à pâte demi-dure",8,"una fontina"],
    [3,"front","un front",8,"un fronte"],
    [6,"fruit","les fruits de mer",8,"i frutti di mare"],
    [6,"fruits","les fruits des bois",8,"i frutti di bosco"],
    [6,"fruits","les fruits",8,"la frutta"],
    [8,"gant","les gants",8,"i guanti"],
    [2,"garçon","un vieux garçon",8,"uno scàpolo"],
    [2,"garde","une garde alternée",8,"un affidamento alternato"],
    [9,"gardien","un gardien",8,"un bidello"],
    [7,"garer","se garer",8,"parcheggiare"],
    [3,"gel","le gel douche/le bain moussant",8,"il bagnoschiuma"],
    [7,"gendarme","les gendarmes",8,"i carabinieri"],
    [2,"gendre","un gendre",8,"un género"],
    [1,"généreux","généreux",8,"generoso"],
    [3,"genou","se mettre à genoux",8,"inginocchiarsi"],
    [3,"genou","un genou",8,"un ginòcchio"],
    [9,"gomme","une gomme (école)",8,"una gomma da cancellare"],
    [6,"gousse","une gousse",8,"uno spìcchio"],
    [3,"goût","un goût",8,"un gusto"],
    [6,"goûter","un goûter (repas)",8,"una merenda"],
    [1,"grand","grand (taille)",8,"alto"],
    [2,"grandir","grandir",8,"créscere"],
    [2,"grand-mère","une grand-mère",8,"una nonna"],
    [2,"grand-père","un grand-père",8,"un nonno"],
    [6,"grappe","une grappe",8,"un gràppolo"],
    [5,"grenier","un grenier",8,"una soffitta"],
    [6,"grillé","grillé (pain)",8,"tostato"],
    [6,"grillé","grillé (viande)",8,"grigliato"],
    [1,"gros","gros",8,"grasso"],
    [1,"grossir","grossir",8,"ingrassare"],
    [6,"gruyère","un gruyère",8,"una groviera"],
    [7,"guichet","un guichet automatique bancaire",8,"un bancomat"],
    [8,"habit","un habit/une robe",8,"un vestito"],
    [6,"hacher","hacher",8,"tritare"],
    [4,"haine","une haine",8,"un òdio"],
    [4,"haïr","haïr",8,"odiare"],
    [5,"hall","un hall",8,"un androne"],
    [6,"haricot","un haricot",8,"un fagiolo"],
    [6,"haricot","un haricot vert",8,"un fagiolino"],
    [5,"hauteur","une hauteur",8,"un'altezza"],
    [6,"herbes","les fines herbes",8,"le erbe aromàtiche"],
    [4,"heureux","heureux",8,"felice"],
    [6,"homard","un homard",8,"un àstice"],
    [1,"homme","un homme",8,"un uomo"],
    [6,"huile","une huile",8,"un òlio"],
    [6,"huître","une huître",8,"un'òstrica"],
    [1,"hypocrite","hypocrite",8,"ipòcrita"],
    [4,"illusion","se faire des illusions",8,"illùdersi"],
    [5,"immeuble","un immeuble",8,"un palazzo"],
    [4,"inattendu","inattendu",8,"inatteso"],
    [4,"incroyable","incroyable",8,"incredìbile"],
    [9,"indiscipliné","indiscipliné",8,"dìscolo"],
    [1,"individu","un individu",8,"un indivìduo"],
    [4,"inquiet","inquiet/agité",8,"inquieto"],
    [4,"inquiéter","s'inquiéter",8,"preoccuparsi"],
    [4,"inquiétude","une inquiétude",8,"un'inquietùdine"],
    [4,"inspirer","inspirer qqch à qqn",8,"incùtere qualcosa a qualcuno"],
    [9,"interroger","interroger",8,"interrogare"],
    [4,"intimidé","être intimidé par",8,"avere soggezione di"],
    [1,"intolérant","intolérant/intransigeant",8,"insofferente"],
    [1,"introverti","introverti",8,"introverso"],
    [3,"jambe","une jambe",8,"una gamba"],
    [6,"jambon","un jambon",8,"un prosciutto"],
    [7,"jardin","un jardin public",8,"un giardino pùbblico"],
    [5,"jaune","jaune",8,"giallo"],
    [1,"jeune","jeune",8,"giòvane"],
    [4,"joie","une joie",8,"una giòia"],
    [1,"joli","joli/mignon",8,"carino"],
    [3,"joue","une joue, les joues",8,"una guància, le guance"],
    [1,"joyeux","joyeux",8,"allegro"],
    [8,"jupe","une jupe",8,"una gonna"],
    [6,"jus","un jus de fruit",8,"un succo di frutta"],
    [8,"kiosque","un kiosque à journaux",8,"un'edìcola"],
    [6,"lait","le lait",8,"il latte"],
    [5,"lampe","une lampe",8,"una làmpada"],
    [6,"langouste","une langouste",8,"un'aragosta"],
    [3,"langue","une langue",8,"una lìngua"],
    [8,"large","large",8,"largo"],
    [5,"largeur","une largeur",8,"una larghezza"],
    [4,"larme","une larme",8,"una làcrima"],
    [6,"laurier","un laurier",8,"un alloro"],
    [5,"lavabo","un lavabo",8,"un lavabo/un lavandino"],
    [3,"laver","se laver",8,"lavarsi"],
    [5,"lave-vaisselle","un lave-vaisselle",8,"una lavastovìglie"],
    [5,"léger","léger",8,"leggero"],
    [6,"légumes","les légumes",8,"la verdura"],
    [3,"lever","se lever",8,"alzarsi"],
    [3,"lèvre","une lèvre, les lèvres",8,"un labbro, le labbra"],
    [9,"licence","une licence",8,"una làurea breve"],
    [5,"liège","le liège",8,"il sùghero"],
    [5,"lit","un lit",8,"un letto"],
    [9,"livre","un livre",8,"un libro"],
    [5,"locataire","un locataire",8,"un inquilino"],
    [1,"long","long",8,"lungo"],
    [5,"longueur","une longueur",8,"una lunghezza"],
    [6,"louche","une louche",8,"un méstolo"],
    [5,"louer","louer",8,"affittare"],
    [5,"lourd","lourd",8,"pesante"],
    [5,"loyer","un loyer",8,"un affitto"],
    [9,"lycée","être au lycée",8,"fare le superiori"],
    [9,"lycée","un lycée professionnel",8,"un istituto técnico"],
    [9,"lycée","un lycée",8,"un liceo"],
    [5,"machine","une machine à laver",8,"una lavatrice"],
    [8,"magasin","un magasin",8,"un negòzio"],
    [8,"magasin","le magasin de vêtements",8,"il negòzio di abbigliamento"],
    [8,"magasin","le magasin de chaussures",8,"il negòzio di scarpe"],
    [1,"maigre","maigre",8,"magro"],
    [1,"maigrir","maigrir",8,"dimagrire"],
    [3,"main","une main, les mains",8,"una mano, le mani"],
    [7,"mairie","une mairie",8,"un municìpio"],
    [5,"maison","la maison",8,"la casa"],
    [9,"maître","un maître",8,"un maestro"],
    [4,"malheur","un malheur (état)",8,"un'infelicità"],
    [2,"maman","une maman",8,"una mamma"],
    [8,"manche","à manches courtes",8,"a màniche corte"],
    [8,"manche","à manches longues",8,"a màniche lunghe"],
    [1,"manie","une manie",8,"una mania"],
    [8,"manteau","un manteau",8,"un cappotto"],
    [3,"maquillage","un maquillage",8,"un trucco"],
    [3,"maquiller","se maquiller",8,"truccarsi"],
    [5,"marbre","un marbre",8,"un marmo"],
    [8,"marché","un marché",8,"un mercato"],
    [3,"marcher","marcher",8,"camminare"],
    [2,"mari","un mari",8,"un marito"],
    [2,"mariage","un mariage",8,"un matrimònio"],
    [2,"marié","les mariés",8,"gli sposi"],
    [1,"marié","marié",8,"sposato/coniugato"],
    [2,"marier","se marier",8,"sposarsi"],
    [5,"marron","marron",8,"marrone"],
    [3,"mascara","un mascara",8,"un mascara/un rimmel"],
    [9,"master","un master",8,"una specialìstica/un master"],
    [5,"matelas","un matelas",8,"un materasso"],
    [9,"maternelle","une maternelle (école)",8,"un asilo/una scuola materna"],
    [6,"mayonnaise","une mayonnaise",8,"una maionese"],
    [4,"mélancolie","une mélancolie",8,"una malinconia"],
    [6,"mélanger","mélanger",8,"mescolare"],
    [9,"mémoire","soutenir son mémoire/sa thèse",8,"discùtere la tesi"],
    [9,"mémoire","un mémoire de master",8,"una tesi di làurea"],
    [1,"menteur","menteur",8,"bugiardo"],
    [3,"menton","un menton",8,"un mento"],
    [4,"mépris","le mépris",8,"il disprezzo"],
    [2,"mère","une mère",8,"una madre"],
    [5,"mesure","une mesure",8,"una misura"],
    [5,"métal","un métal",8,"un metallo"],
    [6,"mettre","mettre la table",8,"apparecchiare"],
    [5,"meubler","meubler/décorer",8,"arredare"],
    [5,"mezzanine","une mezzanine/une mansarde",8,"una mansarda"],
    [1,"mince","mince",8,"snello"],
    [5,"miroir","un miroir",8,"uno spécchio"],
    [1,"moche","moche",8,"brutto"],
    [3,"mollet","un mollet",8,"un polpàccio"],
    [6,"morue","une morue (salée et séchée)",8,"un baccalà"],
    [5,"mou","mou/doux/moelleux",8,"mòrbido"],
    [8,"moulant","moulant",8,"attillato/aderente"],
    [6,"moule","une moule",8,"una cozza"],
    [2,"mourir","mourir",8,"morire"],
    [3,"mousse","une mousse à raser",8,"una schiuma da barba"],
    [1,"moustache","la moustache",8,"i baffi"],
    [6,"moutarde","une moutarde",8,"una sénape"],
    [9,"moyenne","la moyenne",8,"la média"],
    [5,"mur","le mur (intérieur)",8,"la parete"],
    [6,"mûr","mûr",8,"maturo"],
    [1,"musclé","musclé",8,"muscoloso"],
    [7,"musée","un musée",8,"un museo"],
    [6,"myrtille","une myrtille",8,"un mirtillo"],
    [1,"naissance","un lieu de naissance",8,"un luogo di nàscita"],
    [2,"naissance","une naissance",8,"una nàscita"],
    [1,"naissance","une date de naissance",8,"una data di nàscita"],
    [1,"naissance","né à",8,"nato a"],
    [6,"nappe","une nappe",8,"una tovàglia"],
    [5,"nettoyer","nettoyer",8,"pulire"],
    [2,"neveu","un neveu/un petit-fils",8,"un nipote"],
    [3,"nez","un nez",8,"un naso"],
    [2,"nièce","une nièce/une petite-fille",8,"una nipote"],
    [2,"noces","les noces",8,"le nozze"],
    [1,"noir","noir",8,"nero"],
    [1,"nom","un nom de famille",8,"un cognome"],
    [4,"nostalgie","une nostalgie",8,"una nostalgia"],
    [9,"note","mettre une note",8,"dare un voto"],
    [9,"note","une note (école)",8,"un voto"],
    [6,"nourriture","la nourriture",8,"il cibo"],
    [2,"nouveau-né","un nouveau-né",8,"un neonato"],
    [3,"odorat","un odorat",8,"un olfatto"],
    [1,"oeil","un oeil, les yeux",8,"un òcchio, gli occhi"],
    [6,"oeuf","un oeuf, les oeufs",8,"un uovo, le uova"],
    [7,"office","un office du tourisme",8,"un uffìcio del turismo"],
    [6,"oignon","un oignon",8,"una cipolla"],
    [2,"oncle","un oncle",8,"uno zio"],
    [1,"optimiste","optimiste",8,"ottimista"],
    [6,"orange","une orange",8,"un'arància"],
    [5,"orange","orange",8,"aràncio"],
    [3,"oreille","une oreille, les oreilles",8,"un orécchio, le orécchie"],
    [5,"oreiller","un oreiller",8,"un guanciale"],
    [6,"origan","un origan",8,"un orìgano"],
    [5,"osier","un osier",8,"un vìmini"],
    [3,"ouïe","une ouïe (audition)",8,"un udito"],
    [6,"oursin","un oursin",8,"un rìccio di mare"],
    [6,"ouvre-boîte","un ouvre-boîte",8,"un apriscàtole"],
    [6,"ouvre-bouteille","un ouvre-bouteille",8,"un apribottìglie"],
    [6,"pain","un pain",8,"un pane"],
    [5,"palier","un palier",8,"un pianeròttolo"],
    [6,"palourde","une palourde",8,"una vòngola"],
    [6,"pané","pané",8,"impanato/panato"],
    [8,"pantoufle","une pantoufle",8,"una ciabatta"],
    [2,"papa","un papa",8,"un papà/un babbo"],
    [1,"papier","les papiers (état civil)",8,"i documenti"],
    [7,"parc","un parc",8,"un parco"],
    [2,"parent","les parents",8,"i genitori"],
    [6,"parmesan","le parmesan",8,"il parmigiano"],
    [7,"passage","le passage clouté",8,"le strisce/le strisce pedonale"],
    [7,"passant","un passant",8,"un passante"],
    [1,"passeport","un passeport",8,"un passaporto"],
    [6,"passoire","une passoire",8,"uno scolapasta"],
    [6,"passoire","une petite passoire",8,"un colino"],
    [6,"pastèque","une pastèque",8,"un'angùria/un cocòmero"],
    [7,"pâté","un pâté de maisons",8,"un isolato"],
    [6,"pâtes","les pâtes",8,"la pasta"],
    [5,"pavillon","un pavillon (habitation)",8,"un villino"],
    [3,"peau","une peau",8,"una pelle"],
    [3,"peigne","un peigne",8,"un péttine"],
    [3,"peignoir","un peignoir",8,"un accappatòio"],
    [7,"pelouse","une pelouse/un pré",8,"un prato"],
    [5,"penderie","une penderie",8,"una guardaroba"],
    [2,"pension","la pension alimentaire",8,"gli alimenti"],
    [2,"père","un père",8,"un padre"],
    [6,"persil","un persil",8,"un prezzémolo"],
    [1,"peser","peser",8,"pesare"],
    [1,"pessimiste","pessimiste",8,"pessimista"],
    [1,"petit","petit (taille)",8,"basso"],
    [6,"petit-déjeuner","un petit-déjeuner",8,"una prima colazione/una colazione"],
    [4,"peur","avoir peur",8,"avere paura"],
    [4,"peur","une peur",8,"una paura"],
    [3,"pied","un pied",8,"un piede"],
    [7,"piéton","un piéton",8,"un pedone"],
    [6,"piment","un piment",8,"un peperoncino"],
    [3,"pince","une pince à épiler",8,"una pinzetta"],
    [6,"pincée","une pincée",8,"un pìzzico"],
    [7,"place","une place",8,"una piazza"],
    [5,"plafond","un plafond",8,"un soffito"],
    [4,"plaire","plaire/aimer",8,"piacere"],
    [7,"plan","un plan",8,"una piantina"],
    [5,"plancher","un plancher/un grenier",8,"un solàio"],
    [6,"plateau","un plateau (table)",8,"un vassòio"],
    [4,"pleurer","pleurer",8,"piàngere"],
    [6,"poële","une poëlle",8,"una padella"],
    [1,"poids","un poids",8,"un peso"],
    [3,"poignet","un poignet",8,"un polso"],
    [1,"poilu","poilu",8,"peloso"],
    [5,"pointe","une pointe",8,"una punta"],
    [6,"poire","une poire",8,"una pera"],
    [6,"pois","un petit pois",8,"un pisello"],
    [6,"pois","un pois chiche",8,"un ceco"],
    [6,"poisson","un poisson",8,"un pesce"],
    [6,"poitrine","la poitrine/les lardons",8,"la pancetta"],
    [3,"poitrine","une poitrine",8,"un petto"],
    [6,"poivre","le poivre",8,"il pepe"],
    [6,"poivron","un poivron",8,"un peperone"],
    [7,"police","une police",8,"una polizia"],
    [6,"pomme","une pomme",8,"una mela"],
    [7,"pompier","les pompiers",8,"i vìgili del fuoco"],
    [6,"porc","un porc",8,"un maiale"],
    [5,"porte","une porte",8,"una porta"],
    [8,"porter","porter",8,"indossare"],
    [7,"poubelle","une poubelle",8,"un bidone"],
    [6,"poulet","un poulet",8,"un pollo"],
    [1,"prénom","un prénom",8,"un nome"],
    [4,"préoccupé","préoccupé",8,"preoccupato"],
    [1,"présenter","se présenter",8,"presentarsi"],
    [9,"président","un président de l'université",8,"un rettore"],
    [9,"primaire","être à l'école primaire",8,"fare le elementari"],
    [9,"primaire","le primaire",8,"le elementari"],
    [5,"prise","une prise (de courant)",8,"una presa"],
    [8,"prix","un prix",8,"un prezzo"],
    [9,"professeur","un professeur d'université",8,"un docente universitàrio"],
    [5,"profondeur","une profondeur",8,"una profondità"],
    [7,"promener","se promener",8,"passeggiare"],
    [5,"propriétaire","un propriétaire",8,"un proprietàrio"],
    [9,"proviseur","un proviseur",8,"un préside"],
    [6,"prune","une prune",8,"una prugna"],
    [8,"puces","les puces",8,"il mercatino delle pulci"],
    [8,"pull","un pull",8,"un maglione/un pullover"],
    [8,"pull","un pull à col roulé",8,"un dolcevita"],
    [9,"punir","punir",8,"punire"],
    [1,"qualité","une qualité",8,"una qualità/una virtù"],
    [7,"quartier","un quartier",8,"un quartiere"],
    [9,"question","poser des questions",8,"fare domande"],
    [7,"queue","faire la queue",8,"fare la fila"],
    [2,"quitter","se quitter",8,"lasciarsi"],
    [5,"radiateur","un radiateur",8,"un termosifone/un radiatore"],
    [1,"radin","radin",8,"tìrchio"],
    [1,"raffiné","raffiné",8,"raffinato"],
    [4,"rage","une rage",8,"una ràbbia"],
    [6,"raisin","le raisin blanc",8,"l'uva bianca"],
    [6,"raisin","le raisin noir",8,"l'uva nera"],
    [4,"rancoeur","la rancoeur",8,"il rancore"],
    [9,"rang","un rang",8,"una fila"],
    [6,"râpé","râpé",8,"grattuggiato"],
    [6,"râper","râper",8,"grattugiare"],
    [3,"raser","se raser la barbe",8,"farsi la barba"],
    [3,"rasoir","un rasoir",8,"un rasòio"],
    [8,"rayon","un rayon",8,"un reparto"],
    [6,"réchauffer","réchauffer",8,"riscaldare"],
    [9,"redoublant","un redoublant",8,"un ripetente"],
    [9,"redoubler","redoubler",8,"ripétere l'anno"],
    [3,"regarder","regarder",8,"guardare"],
    [9,"règle","une règle (école)",8,"un righello"],
    [3,"règles","les règles (menstrues)",8,"le mestruazioni"],
    [2,"remarier","se remarier",8,"risposarsi"],
    [8,"remise","une remise/une réduction",8,"uno sconto"],
    [9,"remplaçant","un remplaçant",8,"un supplente"],
    [5,"rénover","rénover",8,"ristrutturare"],
    [6,"repas","un repas de midi",8,"un pranzo"],
    [6,"repas","un repas",8,"un pasto"],
    [3,"respiration","la respiration/le souffle",8,"il respiro"],
    [3,"respirer","respirer",8,"respirare"],
    [4,"ressentir","ressentir",8,"provare"],
    [7,"retirer","retirer de l'argent",8,"ritirare dei soldi"],
    [7,"réverbère","un réverbère",8,"un lampione"],
    [9,"réviser","réviser",8,"ripassare"],
    [5,"rez-de-chaussée","un rez-de-chaussée",8,"un pianoterra/un pianterreno"],
    [5,"rideau","un rideau",8,"una tenda"],
    [3,"rincer","se rincer",8,"sciacquarsi"],
    [4,"rire","rire",8,"rìdere"],
    [6,"rissoler","faire revenir/rissoler",8,"far soffrìggere/far rosolare"],
    [6,"riz","le riz",8,"il riso"],
    [5,"robinet","un robinet",8,"un rubinetto"],
    [4,"rogne","se mettre en rogne (familier)",8,"incazzarsi"],
    [6,"romarin","un romarin",8,"un rosmarino"],
    [5,"rond","rond",8,"rotondo/tondo"],
    [7,"rond-point","un rond-point",8,"una rotonda"],
    [5,"rouge","rouge",8,"rosso"],
    [3,"rouge-à-lèvres","un rouge-à-lèvres",8,"un rossetto"],
    [7,"route","une route",8,"una strada"],
    [1,"roux","roux",8,"rosso"],
    [7,"rue","une rue",8,"una via"],
    [7,"ruelle","une ruelle",8,"un vìcolo"],
    [5,"rugueux","rugueux",8,"rùvido"],
    [9,"sac","un sac à dos",8,"uno zàino"],
    [6,"salade","une salade",8,"un'insalata"],
    [5,"sale","sale",8,"sporco"],
    [5,"salle","une salle de bain/des toilettes",8,"un bagno"],
    [5,"salle","une salle à manger",8,"una sala da pranzo"],
    [5,"salon","un salon (pièce)",8,"un salone"],
    [8,"sandale","une sandale",8,"un sandalo"],
    [6,"saucisse","une saucisse",8,"una salsìccia"],
    [6,"saucisson","un saucisson",8,"un salame"],
    [6,"saumon","un saumon",8,"un salmone"],
    [3,"sauter","sauter",8,"saltare"],
    [3,"savon","un savon",8,"un sapone"],
    [4,"scandaleux","scandaleux",8,"scandaloso"],
    [5,"séchoir","un séchoir (à linge)",8,"uno stendino"],
    [4,"se décourager","se décourager",8,"scoraggiarsi"],
    [1,"séduisant","séduisant",8,"attraente"],
    [5,"séjour","un séjour (pièce)",8,"un soggiorno"],
    [6,"sel","le sel",8,"il sale"],
    [1,"sembler","sembler",8,"sembrare"],
    [7,"sens","un sens interdit",8,"un senso vietato"],
    [3,"sentir","sentir (dégager une odeur)",8,"odorare"],
    [2,"séparation","une séparation",8,"una separazione"],
    [1,"séparé","séparé",8,"separato"],
    [2,"séparer","se séparer/rompre",8,"separarsi"],
    [9,"sérieux","sérieux",8,"sério"],
    [8,"serré","serré",8,"stretto"],
    [1,"serviable","serviable",8,"serviziévole"],
    [3,"serviette","une serviette hygiénique",8,"un assorbente"],
    [3,"serviette","une serviette",8,"un asciugamano"],
    [6,"serviette","une serviette (de table)",8,"un tovagliolo"],
    [1,"sexe","un sexe (état civil)",8,"un sesso"],
    [3,"shampooing","un shampooing",8,"uno shampoo"],
    [3,"shampooing","un après-shampooing",8,"un bàlsamo"],
    [8,"shopping","faire du shopping",8,"fare shopping"],
    [1,"sincère","sincère",8,"sincero"],
    [8,"slip","le slip",8,"gli slip"],
    [2,"soeur","une soeur",8,"una sorella"],
    [5,"sol","un sol (maison)",8,"un pavimento"],
    [8,"soldes","les soldes",8,"i saldi"],
    [4,"souffrir","souffrir",8,"soffrire"],
    [4,"soulagé","soulagé",8,"sollevato"],
    [4,"soulagement","un soulagement",8,"un sollievo"],
    [3,"sourcil","un sourcil, les sourcils",8,"un sopraccìglio, le sopraccìglia"],
    [4,"sourire","un sourire",8,"un sorriso"],
    [5,"sous-sol","un sous-sol (maison)",8,"un piano interrato"],
    [8,"soutien-gorge","un soutien-gorge",8,"un reggiseno"],
    [8,"string","un string",8,"un perizoma"],
    [9,"studieux","studieux",8,"studioso"],
    [4,"stupeur","une stupeur",8,"uno stupore"],
    [9,"stylo","un stylo",8,"una penna"],
    [8,"supermarché","un supermarché",8,"un supermercato"],
    [6,"surcre","le sucre",8,"il zùcchero"],
    [1,"surnom","un surnom",8,"un nomignolo/un soprannome"],
    [4,"surprenant","surprenant",8,"stupefacente"],
    [4,"surprise","une surprise",8,"una sorpresa"],
    [8,"survêtement","un survêtement",8,"una tuta"],
    [1,"susceptible","susceptible",8,"permaloso"],
    [8,"sweat-shirt","un sweat-shirt",8,"una felpa"],
    [1,"sympathique","sympatique",8,"simpàtico"],
    [5,"table","une table de chevet",8,"un comodino"],
    [5,"table","une table",8,"un tàvolo"],
    [9,"tableau","un tableau",8,"una lavagna"],
    [1,"taciturne","taciturne",8,"taciturno"],
    [5,"taie","la taie",8,"la fédera"],
    [3,"taille","une taille (partie du corps)",8,"una vita"],
    [1,"taille","une taille (aspect physique)",8,"un'altezza"],
    [8,"talon","un talon",8,"un tacco"],
    [3,"tampon","un tampon hygiénique",8,"un assorbente interno"],
    [2,"tante","une tante",8,"una zia"],
    [5,"tapis","un tapis",8,"un tappeto"],
    [6,"tasse","une tasse",8,"una tazza"],
    [1,"tempérament","un tempérament",8,"un'ìndole"],
    [9,"temps","un emploi du temps",8,"un oràrio"],
    [4,"tendresse","une tendresse",8,"una tenerezza"],
    [5,"terne","terne",8,"spento"],
    [4,"terrifiant","terrifiant",8,"terrificante"],
    [3,"tête","une tête",8,"una testa"],
    [9,"thèse","une thèse",8,"una tesi di dottorato"],
    [6,"thon","un thon",8,"un tonno"],
    [6,"thym","un thym",8,"un timo"],
    [8,"ticket","un ticket de caisse",8,"uno scontrino"],
    [6,"tiède","tiède",8,"tiépido"],
    [1,"timide","timide",8,"tìmido"],
    [6,"tire-bouchon","un tire-bouchon",8,"un cavatappi"],
    [5,"tiroir","un tiroir",8,"un cassetto"],
    [5,"toit","un toit",8,"un tetto"],
    [6,"tomate","une tomate",8,"un pomodoro"],
    [4,"tomber","tomber amoureux",8,"innamorarsi"],
    [6,"torchon","un torchon",8,"uno strofinàccio/uno stràccio"],
    [3,"toucher","un toucher",8,"un tatto"],
    [3,"toucher","toucher",8,"toccare"],
    [3,"transpiration","la transpiration",8,"il sudore"],
    [1,"trapu","trapu",8,"tozzo/tarchiato"],
    [5,"triangulaire","triangulaire",8,"triangolare"],
    [8,"tricot","un tricot",8,"un màglia"],
    [4,"tristesse","une tristesse",8,"una tristezza"],
    [7,"trottoir","un trottoir",8,"un marciapiede"],
    [9,"trousse","une trousse",8,"un astùccio"],
    [8,"t-shirt","un t-shirt",8,"una maglietta/una t-shirt"],
    [2,"tutelle","en tutelle",8,"in affidamento"],
    [2,"union","l'union libre",8,"la còppia di fatto"],
    [7,"urgence","les urgences",8,"il pronto soccorso"],
    [6,"ustensile","les ustensiles",8,"gli uténsili"],
    [6,"vache","de vache",8,"di mucca/vaccino"],
    [1,"vaniteux","vaniteux",8,"vanitoso"],
    [6,"veau","un veau",8,"un vitello"],
    [8,"vendeur","un vendeur",8,"un commesso"],
    [3,"ventre","un ventre",8,"una pància"],
    [3,"vernis","un vernis à ongles",8,"uno smalto"],
    [6,"verre","un verre",8,"un bicchiere"],
    [5,"verre","le verre",8,"il vetro"],
    [5,"vert","vert",8,"verde"],
    [6,"vert","vert (pas mûr)",8,"acerbo"],
    [8,"veste","une veste",8,"una giacca"],
    [1,"veuf","veuf",8,"védovo"],
    [6,"viande","une viande",8,"una carne"],
    [2,"vieillesse","une vieillesse",8,"una vecchiàia"],
    [2,"vieillir","vieillir",8,"invecchiare"],
    [1,"vieux","vieux",8,"vécchio"],
    [5,"vif","vif (couleur)",8,"acceso"],
    [5,"villa","la villa",8,"la villa"],
    [6,"vinaigre","un vinaigre",8,"un aceto"],
    [3,"visage","un visage",8,"un viso"],
    [5,"visiter","visiter",8,"visitare"],
    [2,"vivre","vivre ensemble",8,"convìvere"],
    [3,"voir","voir",8,"vedere"],
    [3,"vue","la vue",8,"la vista"],
    [1,"vulgaire","vulgaire",8,"volgare"],
    [7,"zone","une zone piétonne",8,"un'àrea pedonale"]]

liste.each do |m|
  @m = Mot.find_by(francais: m[2])
  if @m
    @m.category_id = m[0]
    @m.mot_directeur = m[1]
    @m.italien = m[4]
    @m.save!
    User.all.each do |u|
      sc = u.scores_mots.find_by(mot_id: @m.id)
      sc.category_id = m[0]
      sc.save!
    end
  else
    @m = Mot.create(category_id: m[0], mot_directeur: m[1], francais: m[2], italien: m[4])
    User.all.each do |u|
      u.scores_mots.create(mot_id: @m.id, category_id: m[0], compteur: m[3])
    end
  end
end

liste = [
    ["amare",
     [[0, "amo",8],
      [1, "ami",8],
      [2, "ama",8],
      [3, "amiamo",8],
      [4, "amate",8],
      [5, "àmano",8],
      [6, "amavo",8],
      [7, "amavi",8],
      [8, "amava",8],
      [9, "amavamo",8],
      [10, "amavate",8],
      [11, "amàvano",8],
      [12, "amai",1],
      [13, "amasti",1],
      [14, "amò",1],
      [15, "amammo",1],
      [16, "amaste",1],
      [17, "amàrono",1],
      [18, "amerò",8],
      [19, "amerai",8],
      [20, "amerà",8],
      [21, "ameremo",8],
      [22, "amerete",8],
      [23, "ameranno",8],
      [24, "ami",8],
      [25, "ami",8],
      [26, "ami",8],
      [27, "amiamo",8],
      [28, "amiate",8],
      [29, "àmino",8],
      [30, "amassi",2],
      [31, "amassi",2],
      [32, "amasse",2],
      [33, "amàssimo",2],
      [34, "amaste",2],
      [35, "amàssero",2],
      [36, "",0],
      [37, "ama",8],
      [38, "ami",8],
      [39, "amiamo",8],
      [40, "amate",8],
      [41, "àmino",8],
      [42, "amerei",8],
      [43, "ameresti",8],
      [44, "amerebbe",8],
      [45, "ameremmo",8],
      [46, "amereste",8],
      [47, "amerébbero",8],
      [48, "amando",8],
      [49, "amato",8]]],
    ["avere",
     [[0, "ho",8],
      [1, "hai",8],
      [2, "ha",8],
      [3, "abbiamo",8],
      [4, "avete",8],
      [5, "hanno",8],
      [6, "avevo",8],
      [7, "avevi",8],
      [8, "aveva",8],
      [9, "avevamo",8],
      [10, "avevate",8],
      [11, "avévano",8],
      [12, "ebbi",1],
      [13, "avesti",1],
      [14, "ebbe",1],
      [15, "avemmo",1],
      [16, "aveste",1],
      [17, "ébbero",1],
      [18, "avrò",8],
      [19, "avrai",8],
      [20, "avrà",8],
      [21, "avremo",8],
      [22, "avrete",8],
      [23, "avranno",8],
      [24, "àbbia",8],
      [25, "àbbia",8],
      [26, "àbbia",8],
      [27, "abbiamo",8],
      [28, "abbiate",8],
      [29, "àbbiano",8],
      [30, "avessi",2],
      [31, "avessi",2],
      [32, "avesse",2],
      [33, "avéssimo",2],
      [34, "aveste",2],
      [35, "avéssero",2],
      [36, "",0],
      [37, "abbi",8],
      [38, "àbbia",8],
      [39, "abbiamo",8],
      [40, "abbiate",8],
      [41, "àbbiano",8],
      [42, "avrei",8],
      [43, "avresti",8],
      [44, "avrebbe",8],
      [45, "avremmo",8],
      [46, "avreste",8],
      [47, "avrébbero",8],
      [48, "avento",8],
      [49, "avuto",8]]],
    ["crédere",
     [[0, "credo",8],
      [1, "credi",8],
      [2, "crede",8],
      [3, "crediamo",8],
      [4, "credete",8],
      [5, "crédono",8],
      [6, "credevo",8],
      [7, "credevi",8],
      [8, "credeva",8],
      [9, "credevamo",8],
      [10, "credevate",8],
      [11, "credévano",8],
      [12, "credei/credetti",1],
      [13, "credesti",1],
      [14, "credé/credette",1],
      [15, "credemmo",1],
      [16, "credeste",1],
      [17, "credérono/credéttero",1],
      [18, "crederò",8],
      [19, "crederai",8],
      [20, "crederà",8],
      [21, "crederemo",8],
      [22, "crederete",8],
      [23, "crederanno",8],
      [24, "creda",8],
      [25, "creda",8],
      [26, "creda",8],
      [27, "crediamo",8],
      [28, "crediate",8],
      [29, "crédano",8],
      [30, "credessi",2],
      [31, "credessi",2],
      [32, "credesse",2],
      [33, "credéssimo",2],
      [34, "credeste",2],
      [35, "credéssero",2],
      [36, "",0],
      [37, "credi",8],
      [38, "creda",8],
      [39, "crediamo",8],
      [40, "credete",8],
      [41, "crédano",8],
      [42, "crederei",8],
      [43, "crederesti",8],
      [44, "crederebbe",8],
      [45, "crederemmo",8],
      [46, "credereste",8],
      [47, "crederébbero",8],
      [48, "credendo",8],
      [49, "creduto",8]]],
    ["dormire",
     [[0, "dormo",8],
      [1, "dormi",8],
      [2, "dorme",8],
      [3, "dormiamo",8],
      [4, "dormite",8],
      [5, "dòrmono",8],
      [6, "dormivo",8],
      [7, "dormivi",8],
      [8, "dormiva",8],
      [9, "dormivamo",8],
      [10, "dormivate",8],
      [11, "dormìvano",8],
      [12, "dormii",1],
      [13, "dormisti",1],
      [14, "dormì",1],
      [15, "dormimmo",1],
      [16, "dormiste",1],
      [17, "dormìrono",1],
      [18, "dormirò",8],
      [19, "dormirai",8],
      [20, "dormirà",8],
      [21, "dormiremo",8],
      [22, "dormirete",8],
      [23, "dormiranno",8],
      [24, "dorma",8],
      [25, "dorma",8],
      [26, "dorma",8],
      [27, "dormiamo",8],
      [28, "dormiate",8],
      [29, "dòrmano",8],
      [30, "dormissi",2],
      [31, "dormissi",2],
      [32, "dormisse",2],
      [33, "dormìssimo",2],
      [34, "dormiste",2],
      [35, "dormìssero",2],
      [36, "",0],
      [37, "dormi",8],
      [38, "dorma",8],
      [39, "dormiamo",8],
      [40, "dormite",8],
      [41, "dòrmano",8],
      [42, "dormirei",8],
      [43, "dormiresti",8],
      [44, "dormirebbe",8],
      [45, "dormiremmo",8],
      [46, "dormireste",8],
      [47, "dormirébbero",8],
      [48, "dormendo",8],
      [49, "dormito",8]]],
    ["éssere",
     [[0, "sono",8],
      [1, "sei",8],
      [2, "è",8],
      [3, "siamo",8],
      [4, "siete",8],
      [5, "sono",8],
      [6, "ero",8],
      [7, "eri",8],
      [8, "era",8],
      [9, "eravamo",8],
      [10, "eravate",8],
      [11, "érano",8],
      [12, "fui",1],
      [13, "fosti",1],
      [14, "fu",1],
      [15, "fummo",1],
      [16, "foste",1],
      [17, "fùrono",1],
      [18, "sarò",8],
      [19, "sarai",8],
      [20, "sarà",8],
      [21, "saremo",8],
      [22, "sarete",8],
      [23, "saranno",8],
      [24, "sia",8],
      [25, "sia",8],
      [26, "sia",8],
      [27, "siamo",8],
      [28, "siate",8],
      [29, "sìano",8],
      [30, "fossi",2],
      [31, "fossi",2],
      [32, "fosse",2],
      [33, "fòssimo",2],
      [34, "foste",2],
      [35, "fòssero",2],
      [36, "",0],
      [37, "sii",8],
      [38, "sia",8],
      [39, "siamo",8],
      [40, "siate",8],
      [41, "sìano",8],
      [42, "sarei",8],
      [43, "saresti",8],
      [44, "sarebbe",8],
      [45, "saremmo",8],
      [46, "sareste",8],
      [47, "sarébbero",8],
      [48, "essendo",8],
      [49, "stato",8]]],
    ["vedere",
     [[0, "vedo",8],
      [1, "vedi",8],
      [2, "vede",8],
      [3, "vediamo",8],
      [4, "vedete",8],
      [5, "védono",8],
      [6, "vedevo",8],
      [7, "vedevi",8],
      [8, "vedeva",8],
      [9, "vedevamo",8],
      [10, "vedevate",8],
      [11, "vedévano",8],
      [12, "vidi",1],
      [13, "vedesti",1],
      [14, "vide",1],
      [15, "vedemmo",1],
      [16, "vedeste",1],
      [17, "vìdero",1],
      [18, "vedrò",8],
      [19, "vedrai",8],
      [20, "vedrà",8],
      [21, "vedremo",8],
      [22, "vedrete",8],
      [23, "vedranno",8],
      [24, "veda",8],
      [25, "veda",8],
      [26, "veda",8],
      [27, "vediamo",8],
      [28, "vediate",8],
      [29, "védano",8],
      [30, "vedessi",2],
      [31, "vedessi",2],
      [32, "vedesse",2],
      [33, "vedéssimo",2],
      [34, "vedeste",2],
      [35, "vedéssero",2],
      [36, "",0],
      [37, "vedi",8],
      [38, "veda",8],
      [39, "vediamo",8],
      [40, "vedete",8],
      [41, "védano",8],
      [42, "vedrei",8],
      [43, "vedresti",8],
      [44, "vedrebbe",8],
      [45, "vedremmo",8],
      [46, "vedreste",8],
      [47, "vedrébbero",8],
      [48, "vedendo",8],
      [49, "visto/veduto",8]]]]

liste.each do |verbe|
  @verbe = Verbe.find_by(infinitif: verbe[0])
  unless @verbe
    @verbe = Verbe.create(infinitif: verbe[0])
  end
  verbe[1].each do |forme|
    @forme = @verbe.formes.find_by(rang_forme: forme[0])
    if @forme
      @forme.italien = forme[1]
      @forme.save!
    else
      @forme = @verbe.formes.create(rang_forme: forme[0], italien: forme[1])
      User.all.each do |user|
        user.scores_formes.create(forme_id: @forme.id, compteur: forme[2])
      end
    end
  end
end