# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

unless User.exists?
  User.create!({:email => "jmarzin@gmail.com", :admin => true, :password => "51julie2", :password_confirmation => "51julie2" })
end

Mot.destroy_all
ScoresMot.destroy_all
liste = [
    ["accouchement","un accouchement",8,"un parto"],
    ["accoucher","accoucher",8,"partorire"],
    ["adolescence","une adolescence",8,"un'adolescenza"],
    ["adresse","une adresse (postale)",8,"un indirizzo"],
    ["âge","un âge adulte",8,"un'età adulta"],
    ["âge","un âge (état civil)",8,"un'età"],
    ["âgée","une personne âgée",8,"una persona anziana"],
    ["agréable","agréable",8,"gradévole"],
    ["allonger","s'allonger",8,"sdraiarsi"],
    ["ami","un petit ami",8,"un ragazzo"],
    ["amie","une petite amie",8,"una ragazza"],
    ["amusant","amusant",8,"divertente"],
    ["anniversaire","fêter son anniversaire",8,"còmpiere gli anni"],
    ["anniversaire","un anniversaire",8,"un compleanno"],
    ["antipathique","antipathique",8,"antipàtico"],
    ["appeler","s'appeler",8,"chiamarsi"],
    ["asseoir","s'asseoir",8,"sedersi"],
    ["barbe","une barbe",8,"una barba"],
    ["beau","beau",8,"bello"],
    ["beau-frère","un beau-frère",8,"un cognato"],
    ["beau-père","un beau-père (conjoint de la mère)",8,"un patrigno"],
    ["beau-père","le beau-père (père du conjoint)",8,"il suòcero"],
    ["beaux-parents","les beaux-parents",8,"i suòceri"],
    ["belle-mère","une belle-mère (conjoint du père)",8,"una matrigna"],
    ["belle-mère","la belle-mère (mère du conjoint)",8,"la suòcera"],
    ["belle-soeur","une belle-soeur",8,"una cognata"],
    ["blond","blond",8,"biondo"],
    ["bouche","une bouche",8,"una bocca"],
    ["bras","un bras, les bras",8,"un bràccio, le bràccia"],
    ["brosse","une brosse à dents",8,"uno spazzolino da denti"],
    ["brosse","la brosse (à cheveux)",8,"la spàzzola"],
    ["bru","une bru",8,"una nuora"],
    ["brun","brun",8,"moro"],
    ["calme","calme",8,"calmo"],
    ["caractère","un caractère",8,"un caràttere"],
    ["carte","une carte d'identité",8,"una carta d'identità"],
    ["célibataire","une célibataire",8,"una single/una nùbile"],
    ["célibataire","un célibataire",8,"un single/un célibe"],
    ["châtain","châtain",8,"castano"],
    ["chauve","chauve",8,"calvo/pelato"],
    ["cheveux","les cheveux",8,"i capelli"],
    ["cheville","une cheville",8,"una cavìglia"],
    ["clair","clair",8,"claro"],
    ["coiffer","se coiffer",8,"pettinarsi"],
    ["colérique","colérique",8,"collérico"],
    ["compagne","une compagne",8,"una compagna"],
    ["compagnon","un compagnon",8,"un compagno"],
    ["comporter","se comporter",8,"comportarsi"],
    ["coordonnée","les coordonnées (état civil)",8,"i recàpiti"],
    ["costaud","costaud",8,"robusto"],
    ["cou","le cou",8,"il collo"],
    ["coude","un coude",8,"un gòmito"],
    ["courir","courir",8,"còrrere"],
    ["court","court",8,"corto"],
    ["cousin","un cousin",8,"un cugino"],
    ["cousine","une cousine",8,"una cugina"],
    ["crayon","un crayon",8,"una matita"],
    ["crème","une crème",8,"una crema"],
    ["croissance","la croissance",8,"la créscita"],
    ["cuisse","une cuisse",8,"una còscia"],
    ["défaut","un défaut",8,"un difetto"],
    ["demi-frère","un demi-frère",8,"un fratellastro"],
    ["demi-soeur","une demi-soeur",8,"una sorellastra"],
    ["dentifrice","un dentifrice",8,"un dentifrìcio"],
    ["dépensier","dépensier",8,"spendaccione"],
    ["désagréable","désagréable",8,"sgradévole"],
    ["divorce","un divorce",8,"un divòrzio"],
    ["divorcé","divorcé",8,"divorziato"],
    ["divorcer","divorcer",8,"divorziare"],
    ["doigt","un doigt, les doigts",8,"un dito, le dita"],
    ["dos","un dos",8,"una schiena"],
    ["doux","doux",8,"dolce"],
    ["drôle","drôle",8,"buffo"],
    ["écouter","écouter",8,"ascoltare"],
    ["égoïste","égoïste",8,"egoista"],
    ["élancé","élancé",8,"slanciato"],
    ["élevé","bien élevé",8,"educato"],
    ["enfance","une enfance",8,"un'infànzia"],
    ["enfant","les enfants (parenté)",8,"i figli"],
    ["enfant (âge)","l'enfant",8,"il bambino/il bimbo"],
    ["ennuyeux","ennuyeux",8,"noioso"],
    ["entendre","entendre/sentir",8,"sentire"],
    ["enterrement","un enterrement",8,"un funerale"],
    ["épaule","les épaules",8,"le spalle"],
    ["épiler","s'épiler",8,"depilarsi"],
    ["épiler","s'épiler à la cire",8,"farsi la ceretta"],
    ["époux","les époux",8,"i còniugi"],
    ["essuyer","s'essuyer/se sécher",8,"asciugarsi"],
    ["ex-femme","une ex-femme",8,"un'ex-mòglie"],
    ["ex-mari","un ex-mari",8,"un ex-marito"],
    ["extraverti","extraverti",8,"estroverso"],
    ["famille","la famille monoparentale",8,"la famìglia monoparentale"],
    ["femme","la femme (épouse)",8,"la mòglie"],
    ["femme","une femme",8,"una donna"],
    ["fesse","les fesses",8,"il sedere"],
    ["fiancé","un fiancé",8,"un fidanzato"],
    ["fiancée","une fiancée",8,"una fidanzata"],
    ["fiancer","se fiancer",8,"fidanzarsi"],
    ["fille","la fille/l'enfant",8,"la fìglia"],
    ["fille","une vieille fille",8,"una zitella"],
    ["fils","le fils/l'enfant",8,"il fìglio"],
    ["foncé","foncé",8,"scuro"],
    ["fond de teint","un fond de teint",8,"un fondotinta"],
    ["frère","un frère",8,"un fratello"],
    ["front","un front",8,"un fronte"],
    ["garçon","un vieux garçon",8,"uno scàpolo"],
    ["garde","une garde alternée",8,"un affidamento alternato"],
    ["gel","le gel douche/le bain moussant",8,"il bagnoschiuma"],
    ["gendre","un gendre",8,"un género"],
    ["généreux","généreux",8,"generoso"],
    ["genou","un genou",8,"un ginòcchio"],
    ["genou","se mettre à genoux",8,"inginocchiarsi"],
    ["goût","un goût",8,"un gusto"],
    ["grand","grand (taille)",8,"alto"],
    ["grandir","grandir",8,"créscere"],
    ["grand-mère","une grand-mère",8,"una nonna"],
    ["grand-père","un grand-père",8,"un nonno"],
    ["gros","gros",8,"grasso"],
    ["grossir","grossir",8,"ingrassare"],
    ["homme","un homme",8,"un uomo"],
    ["hypocrite","hypocrite",8,"ipòcrita"],
    ["individu","un individu",8,"un indivìduo"],
    ["intolérant","intolérant/intransigeant",8,"insofferente"],
    ["introverti","introverti",8,"introverso"],
    ["jambe","une jambe",8,"una gamba"],
    ["jeune","jeune",8,"giòvane"],
    ["joli","joli/mignon",8,"carino"],
    ["joue","une joue, les joues",8,"una guància, le guance"],
    ["joyeux","joyeux",8,"allegro"],
    ["langue","une langue",8,"una lìngua"],
    ["laver","se laver",8,"lavarsi"],
    ["lever","se lever",8,"alzarsi"],
    ["lèvre","une lèvre, les lèvres",8,"un labbro, le labbra"],
    ["long","long",8,"lungo"],
    ["maigre","maigre",8,"magro"],
    ["maigrir","maigrir",8,"dimagrire"],
    ["main","une main, les mains",8,"una mano, le mani"],
    ["maman","une maman",8,"una mamma"],
    ["manie","une manie",8,"una mania"],
    ["maquillage","un maquillage",8,"un trucco"],
    ["maquiller","se maquiller",8,"truccarsi"],
    ["marcher","marcher",8,"camminare"],
    ["mari","un mari",8,"un marito"],
    ["mariage","un mariage",8,"un matrimònio"],
    ["marié","les mariés",8,"gli sposi"],
    ["marié","marié",8,"sposato/coniugato"],
    ["marier","se marier",8,"sposarsi"],
    ["mascara","un mascara",8,"un mascara/un rimmel"],
    ["menteur","menteur",8,"bugiardo"],
    ["menton","un menton",8,"un mento"],
    ["mère","une mère",8,"una madre"],
    ["mince","mince",8,"snello"],
    ["moche","moche",8,"brutto"],
    ["mollet","un mollet",8,"un polpàccio"],
    ["mourir","mourir",8,"morire"],
    ["mousse","une mousse à raser",8,"una schiuma da barba"],
    ["moustache","la moustache",8,"i baffi"],
    ["musclé","musclé",8,"muscoloso"],
    ["naissance","né à",8,"nato a"],
    ["naissance","un lieu de naissance",8,"un luogo di nàscita"],
    ["naissance","une date de naissance",8,"una data di nàscita"],
    ["naissance","une naissance",8,"una nàscita"],
    ["neveu","un neveu/un petit-fils",8,"un nipote"],
    ["nez","un nez",8,"un naso"],
    ["nièce","une nièce/une petite-fille",8,"una nipote"],
    ["noces","les noces",8,"le nozze"],
    ["noir","noir",8,"nero"],
    ["nom","un nom de famille",8,"un cognome"],
    ["nouveau-né","un nouveau-né",8,"un neonato"],
    ["odorat","un odorat",8,"un olfatto"],
    ["oeil","un oeil, les yeux",8,"un òcchio, gli occhi"],
    ["oncle","un oncle",8,"uno zio"],
    ["optimiste","optimiste",8,"ottimista"],
    ["oreille","une oreille, les oreilles",8,"un orécchio, le orécchie"],
    ["ouïe","une ouïe (audition)",8,"un udito"],
    ["papa","un papa",8,"un papà/un babbo"],
    ["papier","les papiers (état civil)",8,"i documenti"],
    ["parent","les parents",8,"i genitori"],
    ["passeport","un passeport",8,"un passaporto"],
    ["peau","une peau",8,"una pelle"],
    ["peigne","un peigne",8,"un péttine"],
    ["peignoir","un peignoir",8,"un accappatòio"],
    ["pension","la pension alimentaire",8,"gli alimenti"],
    ["père","un père",8,"un padre"],
    ["peser","peser",8,"pesare"],
    ["pessimiste","pessimiste",8,"pessimista"],
    ["petit","petit (taille)",8,"basso"],
    ["pied","un pied",8,"un piede"],
    ["pince","une pince à épiler",8,"una pinzetta"],
    ["poids","un poids",8,"un peso"],
    ["poignet","un poignet",8,"un polso"],
    ["poilu","poilu",8,"peloso"],
    ["poitrine","une poitrine",8,"un petto"],
    ["prénom","un prénom",8,"un nome"],
    ["présenter","se présenter",8,"presentarsi"],
    ["qualité","une qualité",8,"una qualità/una virtù"],
    ["quitter","se quitter",8,"lasciarsi"],
    ["radin","radin",8,"tìrchio"],
    ["raffiné","raffiné",8,"raffinato"],
    ["raser","se raser la barbe",8,"farsi la barba"],
    ["rasoir","un rasoir",8,"un rasòio"],
    ["regarder","regarder",8,"guardare"],
    ["règles","les règles (menstrues)",8,"le mestruazioni"],
    ["remarier","se remarier",8,"risposarsi"],
    ["respiration","la respiration/le souffle",8,"il respiro"],
    ["respirer","respirer",8,"respirare"],
    ["rincer","se rincer",8,"sciacquarsi"],
    ["rouge-à-lèvres","un rouge-à-lèvres",8,"un rossetto"],
    ["roux","roux",8,"rosso"],
    ["sauter","sauter",8,"saltare"],
    ["savon","un savon",8,"un sapone"],
    ["séduisant","séduisant",8,"attraente"],
    ["sembler","sembler",8,"sembrare"],
    ["sentir","sentir (dégager une odeur)",8,"odorare"],
    ["séparation","une séparation",8,"una separazione"],
    ["séparé","séparé",8,"separato"],
    ["séparer","se séparer/rompre",8,"separarsi"],
    ["serviable","serviable",8,"serviziévole"],
    ["serviette","une serviette",8,"un asciugamano"],
    ["serviette","une serviette hygiénique",8,"un assorbente"],
    ["sexe","un sexe (état civil)",8,"un sesso"],
    ["shampooing","un shampooing",8,"uno shampoo"],
    ["shampooing","un après-shampooing",8,"un bàlsamo"],
    ["sincère","sincère",8,"sincero"],
    ["soeur","une soeur",8,"una sorella"],
    ["sourcil","un sourcil, les sourcils",8,"un sopraccìglio, le sopraccìglia"],
    ["surnom","un surnom",8,"un nomignolo/un soprannome"],
    ["susceptible","susceptible",8,"permaloso"],
    ["sympathique","sympatique",8,"simpàtico"],
    ["taciturne","taciturne",8,"taciturno"],
    ["taille","une taille (partie du corps)",8,"una vita"],
    ["taille","une taille (aspect physique)",8,"un'altezza"],
    ["tampon","un tampon hygiénique",8,"un assorbente interno"],
    ["tante","une tante",8,"una zia"],
    ["tempérament","un tempérament",8,"un'ìndole"],
    ["tête","une tête",8,"una testa"],
    ["timide","timide",8,"tìmido"],
    ["toucher","toucher",8,"toccare"],
    ["toucher","un toucher",8,"un tatto"],
    ["transpiration","la transpiration",8,"il sudore"],
    ["trapu","trapu",8,"tozzo/tarchiato"],
    ["tutelle","en tutelle",8,"in affidamento"],
    ["union","l'union libre",8,"la còppia di fatto"],
    ["vaniteux","vaniteux",8,"vanitoso"],
    ["ventre","un ventre",8,"una pància"],
    ["vernis","un vernis à ongles",8,"uno smalto"],
    ["veuf","veuf",8,"védovo"],
    ["vieillesse","une vieillesse",8,"una vecchiàia"],
    ["vieillir","vieillir",8,"invecchiare"],
    ["vieux","vieux",8,"vécchio"],
    ["visage","un visage",8,"un viso"],
    ["vivre","vivre ensemble",8,"convìvere"],
    ["voir","voir",8,"vedere"],
    ["vue","la vue",8,"la vista"],
    ["vulgaire","vulgaire",8,"volgare"]]
liste.each do |m|
  @m = Mot.create(mot_directeur: m[0], francais: m[1], italien: m[3])
  @m.save
  User.all.each do |u|
    u.scores_mots.build(user_id: u.id,mot_id: @m.id,compteur: m[2])
    u.save
  end
end

Verbe.destroy_all
Forme.destroy_all
ScoresForme.destroy_all
liste = [
    ["amare",
     [[0, "amo",8],
      [1, "ami",8],
      [2, "ama",8],
      [3, "amiamo",8],
      [4, "amate",8],
      [5, "àmano",8],
      [6, "amavo",8],
      [7, "amavi",8],
      [8, "amava",8],
      [9, "amavamo",8],
      [10, "amavate",8],
      [11, "amàvano",8],
      [12, "amai",1],
      [13, "amasti",1],
      [14, "amò",1],
      [15, "amammo",1],
      [16, "amaste",1],
      [17, "amàrono",1],
      [18, "amerò",8],
      [19, "amerai",8],
      [20, "amerà",8],
      [21, "ameremo",8],
      [22, "amerete",8],
      [23, "ameranno",8],
      [24, "ami",8],
      [25, "ami",8],
      [26, "ami",8],
      [27, "amiamo",8],
      [28, "amiate",8],
      [29, "àmino",8],
      [30, "amassi",2],
      [31, "amassi",2],
      [32, "amasse",2],
      [33, "amàssimo",2],
      [34, "amaste",2],
      [35, "amàssero",2],
      [36, "",0],
      [37, "ama",8],
      [38, "ami",8],
      [39, "amiamo",8],
      [40, "amate",8],
      [41, "àmino",8],
      [42, "amerei",8],
      [43, "ameresti",8],
      [44, "amerebbe",8],
      [45, "ameremmo",8],
      [46, "amereste",8],
      [47, "amerébbero",8],
      [48, "amando",8],
      [49, "amato",8]]]]
liste.each do |verbe|
  @verbe = Verbe.create(infinitif: verbe[0])
  verbe[1].each do |forme|
    @forme = @verbe.formes.create(rang_forme: forme[0], italien: forme[1])
    User.all.each do |user|
      user.scores_formes.create(forme_id: @forme.id, compteur: forme[2])
    end
  end
end