# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

unless User.exists?
  User.create!({:email => "jmarzin@gmail.com", :admin => true, :password => "51julie2", :password_confirmation => "51julie2" })
end

liste = [
    [1,"L'individu"],
    [2,"La famille"],
    [3,"Le corps"],
    [4,"Les sentiments et les émotions"],
    [5,"La maison"],
    [6,"La cuisine et les repas"],
    [7,"La ville"],
    [8,"Les courses"],
    [9,"L'éducation"],
    [10,"Le travail"],
    [11,"La santé"],
    [12,"Les voyages et les sorties"],
    [13,"Les arts et les loisirs"],
    [14,"Les sports"],
    [15,"Le temps qu'il fait, le temps qui passe"],
    [16,"La nature et l'environnement"],
    [17,"Les médias"],
    [18,"Les techniques de communication"],
    [19,"La vie en société"],
    [20,"La politique"],
    [21,"Pensée, opinion, croyance"],
    [22,"Du français à l'italien"]]

liste.each do |c|
  @c = Category.find_by(numero: c[0])
  if @c
    @c.description = c[1]
    @c.save!
  else
    @c = Category.create(numero: c[0], description: c[1])
  end
end

liste = [
    [22,"à","une tasse à café",1,"una tazzina da caffè"],
    [22,"à","au lit",1,"a letto"],
    [22,"à","à la différence de",1,"a differenza di"],
    [22,"à","à la messe",1,"a messa"],
    [22,"à","au hasard",1,"a caso"],
    [22,"à","au contact de",1,"a contatto con"],
    [22,"à","à la télé",1,"in tivù"],
    [22,"à","au bureau",1,"in uffìcio"],
    [22,"à","à la maison",1,"a casa"],
    [22,"à","à l'heure",1,"in oràrio"],
    [22,"à","à la bibliothèque",1,"in biblioteca"],
    [22,"à","à la piscine",1,"in piscina"],
    [22,"à","à la campagne",1,"in campagna"],
    [22,"à","à la banque",1,"in banca"],
    [22,"à","j'ai beaucoup de choses à faire",1,"ho molte cose da fare"],
    [22,"à","qui est cette fille aux yeux bleus ?",1,"chi è la ragazza con gli occhi azzurri?"],
    [22,"à","ces gants sont à lui",1,"questi guanti sono suoi"],
    [22,"à","à qui est-ce ?",1,"di chi è?"],
    [22,"à","au dix-neuvième siècle",1,"nel diciannovésimo sécolo"],
    [22,"à","à minuit",1,"a mezzanotte"],
    [22,"à","à midi",1,"a mezzogiorno"],
    [22,"à","à 5 heures",1,"alle cinque"],
    [22,"à","ce livre est à Giani",1,"questo libro è di Giani"],
    [22,"à","à l'école",1,"a scuola"],
    [22,"à","à la montagne",1,"in montagna"],
    [22,"à","au printemps",1,"in primavera"],
    [22,"à","ces chaussures sont à elle",1,"queste scarpe sono sue"],
    [22,"à","au théâtre",1,"a teatro"],
    [16,"abeille","une abeille",8,"un'ape"],
    [16,"aboyer","aboyer",8,"abbaiare"],
    [7,"abribus","un abribus",1,"una pensilina"],
    [6,"abricot","un abricot",1,"un'albicocca"],
    [22,"accident","un accident de la route",1,"un incidente/un incidente stradale"],
    [22,"accident","un accident du travail",1,"un infortùnio sul lavoro/un infortùnio"],
    [22,"accident","les accidents de la vie",1,"i casi della vita"],
    [12,"accompagnement","un accompagnement (repas)",8,"un contorno"],
    [13,"accordéon","un accordéon",8,"una fisarmònica"],
    [2,"accouchement","un accouchement",1,"un parto"],
    [2,"accoucher","accoucher",1,"partorire"],
    [5,"accueillant","accueillant",1,"accogliente"],
    [5,"acheter","acheter",1,"comprare"],
    [5,"acier","un acier",1,"un acciàio"],
    [5,"acompte","un acompte",1,"un acconto"],
    [13,"acteur","un acteur",8,"un attore"],
    [13,"actrice","un actrice",8,"un'attrice"],
    [12,"addition","une addition",8,"un conto"],
    [2,"adolescence","une adolescence",1,"un'adolescenza"],
    [1,"adresse","une adresse (postale)",1,"un indirizzo"],
    [22,"adresser","Veuillez adresser ce colis à l'adresse suivante...",1,"La prego di spedire questo pacco all'indirizzo seguente..."],
    [22,"adresser","il ne m'a plus adressé la parole",1,"non mi ha più rivolto la parola"],
    [22,"adresser","à qui faut-il adresser cette lettre ?",1,"a chi va indirizzata questa léttera?"],
    [22,"adresser","nous vous adressons nos meilleurs voeux",1,"vi mandiamo i nostri migliori auguri"],
    [22,"adresser","l'acteur s'est directement adressé au public",1,"l'attore si è direttamente rivolto al pùbblico"],
    [22,"adresser","addressez-vous à l'office du tourisme",1,"rivolgétevi all'uffìcio del turismo"],
    [22,"adresser","nous adressons nos compliments au vainqueur",1,"rivolgiamo i nostri complimenti al vincitore"],
    [12,"aéroport","un aéroport",8,"un aeroporto"],
    [4,"affection","une affection",1,"un affetto"],
    [4,"affectueux","affectueux",1,"affettuoso"],
    [6,"affiné","affiné",1,"stagionato"],
    [4,"affligé","affligé",1,"afflitto"],
    [1,"âge","un âge (état civil)",1,"un'età"],
    [2,"âge","un âge adulte",1,"un'età adulta"],
    [2,"âgée","une personne âgée",1,"una persona anziana"],
    [5,"agence","une agence immobilière",1,"un'agenzia immobiliare"],
    [12,"agence","un agence de voyage",8,"un'agenzia di viaggi"],
    [9,"agenda","un agenda/un cahier de textes",1,"un diàrio"],
    [14,"agile","agile",8,"àgile"],
    [4,"agité","agité",1,"agitato/mosso"],
    [6,"agneau","un agneau",1,"un agnello"],
    [1,"agréable","agréable",1,"gradévole"],
    [16,"agriculture","une agriculture biologique",8,"un'agricoltura biològica"],
    [6,"agrume","les agrumes",1,"gli agrumi"],
    [16,"aigle","un aigle",8,"un'àquila"],
    [6,"ail","un ail",1,"un àglio"],
    [4,"aimer","aimer (un ami)",1,"voler bene a"],
    [4,"aimer","aimer",1,"amare"],
    [16,"air","un air (climat)",8,"un'ària"],
    [11,"aller","aller mieux",1,"migliorare"],
    [11,"aller","aller bien",1,"stare bene"],
    [11,"aller","aller mal",1,"stare male"],
    [11,"allergie","une allergie",1,"un'allergia"],
    [3,"allonger","s'allonger",1,"sdraiarsi"],
    [13,"aménagement","un aménagement (exposition)",8,"un allestimento"],
    [5,"aménager","aménager",1,"sistemare"],
    [2,"ami","un petit ami",1,"un ragazzo"],
    [4,"ami","le meilleur ami",1,"l'amico del cuore"],
    [2,"amie","une petite amie",1,"una ragazza"],
    [4,"amitié","une amitié",1,"un'amicìzia"],
    [4,"amour","un amour",1,"un amore"],
    [4,"amoureux","amoureux",1,"innamorato"],
    [5,"ampoule","une ampoule (éclairage)",1,"una lampadina"],
    [1,"amusant","amusant",1,"divertente"],
    [12,"amuser","s'amuser",8,"divertirsi"],
    [15,"ancien","ancien",8,"antico"],
    [5,"angle","un angle",1,"un àngolo"],
    [4,"angoisse","une angoisse/une anxiété",1,"un'angòscia/un'ànsia"],
    [4,"angoissé","angoissé",1,"ansioso"],
    [7,"animé","animé",1,"animato"],
    [15,"année","une année",8,"un anno"],
    [2,"anniversaire","un anniversaire",1,"un compleanno"],
    [2,"anniversaire","fêter son anniversaire",1,"còmpiere gli anni"],
    [10,"annonce","une petite annonce",1,"un annùncio di lavoro"],
    [5,"annonce","une annonce immobilière",1,"un annùncio immobiliare"],
    [12,"annuler","annuler",8,"annullare/disdire"],
    [15,"anticiper","anticiper",8,"anticipare"],
    [1,"antipathique","antipathique",1,"antipàtico"],
    [12,"apéritif","un apéritif",8,"un aperitivo"],
    [5,"appartement","un appartement",1,"un appartamento"],
    [1,"appeler","s'appeler",1,"chiamarsi"],
    [12,"appeler","appeler un taxi",8,"chiamare un taxi"],
    [13,"applaudir","applaudir",8,"applaudire"],
    [9,"apprendre","apprendre",1,"imparare"],
    [10,"apprenti","un apprenti",1,"un'apprendista"],
    [16,"apprivoisé","apprivoisé",8,"addomesticato"],
    [15,"après-midi","un après-midi",8,"un pomerìggio"],
    [13,"aquarelle","une aquarelle",8,"un acquarello"],
    [16,"araignée","une araignée",8,"un ragno"],
    [16,"arbre","un arbre",8,"un àlbero"],
    [15,"arc-en-ciel","un arc-en-ciel",8,"un arcobaleno"],
    [10,"architecte","un architecte",1,"un architetto"],
    [5,"armoire","une armoire/un placard",1,"un armàdio"],
    [12,"arrêt","faire un arrêt",8,"fare una sosta"],
    [11,"arrêt","un arrêt cardiaque",1,"un arresto cardìaco"],
    [12,"arrêt","un arrêt",8,"una fermata"],
    [5,"arrhes","les arrhes",1,"la caparra"],
    [12,"arrivée","une arrivée",8,"un arrivo"],
    [6,"artichaud","un artichaud",1,"un carciofo"],
    [13,"article","un article",8,"un artìcolo"],
    [2,"asseoir","s'asseoir",1,"sedersi"],
    [4,"assez","en avoir assez",1,"stufarsi"],
    [6,"assiette","une assiette creuse",1,"un piatto fondo"],
    [6,"assiette","une assiette",1,"un piatto"],
    [14,"athlétisme","un athlétisme",8,"un'atlética"],
    [7,"attendre","attendre son tour",1,"aspettare il pròprio turno"],
    [9,"attentif","attentif",1,"attento"],
    [12,"atterrir","atterri",8,"atterrare"],
    [12,"atterrissage","un atterrissage",8,"un atterràggio"],
    [4,"attristé","attristé",1,"rattristato"],
    [15,"aube","une aube",8,"un'alba"],
    [12,"auberge","une auberge",8,"un ostello"],
    [6,"aubergine","une aubergine",1,"una melanzana"],
    [10,"augmentation","une augmentation",1,"un aumento"],
    [13,"auteur","un auteur-compositeur",8,"un cantautore"],
    [12,"authentique","authentique",8,"genuino"],
    [12,"autocar","un autocar",8,"un pullman"],
    [15,"automne","un automne",8,"un autunno"],
    [12,"autoroute","une autoroute",8,"un'autostrada"],
    [11,"avaler","avaler",1,"ingoiare"],
    [15,"avance","être en avance",8,"éssere in antìcipo"],
    [15,"avenir","un avenir",8,"un avvenire"],
    [15,"averse","une averse",8,"un acquazzone"],
    [14,"avertissement","un avertissement",8,"un'ammonizione"],
    [12,"avion","un avion",8,"un aéreo"],
    [10,"avocat","un avocat",1,"un avvocato"],
    [9,"baccalauréat","le baccalauréat",1,"la maturità"],
    [12,"bagage","un bagage à main",8,"un bagàglio a mano"],
    [16,"baie","une baie (mer)",8,"una bàia"],
    [5,"baignoire","une baignoire",1,"una vasca"],
    [4,"baiser","un baiser",1,"un bàccio"],
    [7,"balançoire","une balançoire",1,"un'altalena"],
    [13,"balcon","un balcon (spectacle)",8,"una galleria"],
    [14,"ballon","un ballon",8,"una palla/un pallone"],
    [9,"banc","un banc (école)",1,"un banco"],
    [7,"banc","un banc (public)",1,"una panchina"],
    [11,"bandage","un bandage",1,"una benda"],
    [13,"bande","une bande dessinée",8,"un fumetto"],
    [7,"banlieue","une banlieue",1,"una periferia"],
    [7,"banque","une banque",1,"una banca"],
    [12,"bar","un bar à vin",8,"un'enoteca"],
    [6,"bar","un bar/un loup",1,"una spìgola"],
    [1,"barbe","une barbe",1,"una barba"],
    [5,"bariolé","bariolé/bigarré",1,"variopinto"],
    [8,"bas","les bas",1,"le calze"],
    [6,"basilic","un basilic",1,"un basìlico"],
    [14,"basket","le basket-ball",8,"la pallacanestro/il basket"],
    [13,"basse","une basse (instrument)",8,"un basso"],
    [12,"bateau","un bateau",8,"un nave"],
    [13,"batterie","une batterie",8,"una batteria"],
    [9,"bavard","bavard",1,"chiacchierone"],
    [1,"beau","beau",1,"bello"],
    [2,"beau-frère","un beau-frère",1,"un cognato"],
    [2,"beau-père","un beau-père (conjoint de la mère)",1,"un patrigno"],
    [2,"beau-père","le beau-père (père du conjoint)",1,"il suòcero"],
    [2,"beaux-parents","les beaux-parents",1,"i suòceri"],
    [2,"belle-mère","une belle-mère (conjoint du père)",1,"una matrigna"],
    [2,"belle-mère","la belle-mère (mère du conjoint)",1,"la suòcera"],
    [2,"belle-soeur","une belle-soeur",1,"una cognata"],
    [16,"belvédère","un belvédère",8,"un belvedere"],
    [13,"best-seller","un best-seller",8,"un best seller"],
    [6,"beurre","le beurre",1,"il burro"],
    [5,"bibliothèque","une bibliothèque (meuble)",1,"una libreria"],
    [13,"bibliothèque","une bibliothèque (lieu)",8,"una biblioteca"],
    [12,"bière","une bière",8,"una birra"],
    [12,"bière","une bière double malt",8,"una birra dòppio malto"],
    [12,"bière","une bière crue (non pasteurisée)",8,"una birra cruda"],
    [12,"bière","une bière pression",8,"una birra alla spina"],
    [12,"bière","une bière ambrée",8,"una birra ambrata"],
    [12,"bière","une bière brune",8,"una birra scura"],
    [12,"bière","une bière rousse",8,"una birra rossa"],
    [12,"bière","une bière blonde",8,"una birra chiara"],
    [10,"bilan","un bilan",1,"un bilàncio"],
    [12,"billet","un billet",8,"un biglietto"],
    [12,"billetterie","un billetterie",8,"una biglietteria"],
    [12,"biologique","biologique",8,"biològico"],
    [12,"biscuit","les biscuits apéritifs",8,"i salatini"],
    [5,"blanc","blanc",1,"bianco"],
    [4,"blessé","blessé",1,"ferito"],
    [11,"blessé","un blessé",1,"un ferito"],
    [11,"blesser","se blesser",1,"ferirsi"],
    [11,"blessure","une blessure",1,"una ferita"],
    [5,"bleu","bleu",1,"blu"],
    [5,"bleu","bleu ciel",1,"celeste"],
    [13,"bloguer","bloguer",8,"bloggare"],
    [1,"blond","blond",1,"biondo"],
    [16,"boeuf","un boeuf",8,"un bue"],
    [6,"boeuf","le boeuf (viande)",1,"il manzo"],
    [12,"boire","boire",8,"bere"],
    [5,"bois","le bois",1,"il legno"],
    [16,"bois","un bois",8,"un bosco"],
    [12,"boisson","une boisson",8,"una bevanda"],
    [7,"boîte","une boîte aux lettres (dans la rue)",1,"una buca delle léttere"],
    [12,"boîte","une boîte de nuit",8,"una discoteca"],
    [6,"bol","un bol",1,"una scodella"],
    [4,"bonheur","un bonheur",1,"una felicità"],
    [5,"bord","un bord",1,"un bordo"],
    [8,"botte","une botte",1,"una stivale"],
    [3,"bouche","une bouche",1,"una bocca"],
    [10,"boucher","un boucher",1,"un macellàio"],
    [8,"boucherie","une boucherie",1,"una macelleria"],
    [6,"bouillir","bouillir",1,"bollire"],
    [10,"boulanger","un boulanger",1,"un panettiere"],
    [8,"boulangerie","une boulangerie",1,"una panetteria/il forno"],
    [7,"boulevard","un boulevard",1,"un viale"],
    [7,"boulevard","un boulevard/une avenue",1,"un corso"],
    [4,"bouleversant","bouleversant",1,"sconvolgente"],
    [6,"bouquet","le bouquet garni",1,"gli odori"],
    [6,"bouquet","un bouquet/une botte",1,"un mazzo"],
    [9,"bourse","une bourse (école)",1,"una borsa di stùdio"],
    [11,"bouton","un bouton (santé)",1,"un brùfolo"],
    [14,"boxe","la boxe",8,"il pugilato"],
    [16,"branche","une branche",8,"un ramo"],
    [3,"bras","un bras, les bras",1,"un bràccio, le bràccia"],
    [14,"brasse","la brasse",8,"la rana"],
    [16,"brebis","une brebis",8,"una pécora"],
    [6,"brebis","de brebis",1,"di pécora/pecorino"],
    [13,"bricolage","un bricole",8,"un fai da te"],
    [13,"broder","broder",8,"ricamare"],
    [13,"broderie","une broderie",8,"un ricamo"],
    [11,"bronchite","une bronchite",1,"una bronchite"],
    [3,"brosse","la brosse (à cheveux)",1,"la spàzzola"],
    [3,"brosse","une brosse à dents",1,"uno spazzolino da denti"],
    [15,"brouillard","un brouillard",8,"una nébbia"],
    [2,"bru","une bru",1,"una nuora"],
    [6,"brûlé","brûlé",1,"bruciato"],
    [15,"brume","une brume",8,"una foschia"],
    [1,"brun","brun",1,"moro"],
    [7,"bruyant","bruyant",1,"rumoroso"],
    [5,"buanderie","une buanderie",1,"una lavanderia"],
    [15,"buée","une buée",8,"una condensa"],
    [6,"bufflonne","de bufflonne",1,"di bùfala"],
    [16,"buisson","un buisson",8,"un cespùglio"],
    [9,"bulletin","un bulletin scolaire",1,"una pagella"],
    [5,"bureau","un bureau (meuble)",1,"una scrivania"],
    [7,"bureau","un bureau de poste",1,"un uffìcio postale"],
    [5,"bureau","un bureau (pièce)",1,"uno stùdio"],
    [9,"bureau","un bureau (de l'enseignant)",1,"una càttedra"],
    [10,"bureau","un bureau (lieu)",1,"un uffìcio"],
    [12,"bus","un bus",8,"un àutobus"],
    [14,"but","un but",8,"un goal/una rete"],
    [6,"cabillaud","un cabillot/une morue",1,"un merluzzo"],
    [11,"cachet","un cachet (médicament)",1,"una pasticca"],
    [8,"caddie","un caddie",1,"un carrello"],
    [12,"cadeau","un cadeau",8,"un regalo"],
    [10,"cadre","un cadre (travail)",1,"un quadro"],
    [12,"café","un café frappé",8,"un caffè shakerato"],
    [12,"café","un café au lait",8,"un caffelatte"],
    [12,"café","un café avec une goutte d'alcool",8,"un caffè corretto"],
    [12,"café","un café noisette",8,"un caffè macchiato"],
    [12,"café","un café serré",8,"un caffè ristretto"],
    [12,"café","un café",8,"un caffè"],
    [14,"cage","une cage (football)",8,"una porta"],
    [9,"cahier","un cahier",1,"un quaderno"],
    [10,"caissier","un caissier",1,"un cassiere"],
    [8,"caleçon","le caleçon",1,"i boxer"],
    [1,"calme","calme",1,"calmo"],
    [12,"caméra","une caméra",8,"una telecàmera/una màcchina da presa"],
    [12,"camping","un camping",8,"un campéggio"],
    [5,"canapé","un canapé",1,"un divano"],
    [6,"canard","un canard",1,"un'ànatra"],
    [11,"cancer","un cancer",1,"un cancro"],
    [9,"cancre","un cancre",1,"un somaro"],
    [10,"candidature","une candidature",1,"una candidatura"],
    [12,"cappuccino","un cappuccino",8,"un cappuccino"],
    [12,"car","un car",8,"una corriera"],
    [1,"caractère","un caractère",1,"un caràttere"],
    [6,"carotte","une carotte",1,"una carota"],
    [5,"carré","carré",1,"quadrato"],
    [10,"carrière","une carrière",1,"una carriera"],
    [9,"cartable","un cartable/un dossier",1,"una cartella"],
    [1,"carte","une carte d'identité",1,"una carta d'identità"],
    [16,"cascade","une cascade",8,"una cascata"],
    [6,"casserole","une casserolle/une marmite",1,"una péntola"],
    [5,"cave","une cave",1,"una cantina"],
    [8,"ceinture","une ceinture",1,"una cinta/una cintura"],
    [6,"céleri","le céleri",1,"il sédano"],
    [1,"célibataire","un célibataire",1,"un single/un célibe"],
    [1,"célibataire","une célibataire",1,"una single/una nùbile"],
    [7,"centre","un centre historique",1,"un centro stòrico"],
    [8,"centre","un centre commercial",1,"un centro commerciale"],
    [7,"centre","un centre-ville",1,"un centro"],
    [6,"céréales","les céréales",1,"i cereali"],
    [5,"chaise","une chaise",1,"una sédia"],
    [15,"chaleur","une chaleur",8,"un caldo"],
    [12,"chambre","une chambre simple",8,"una sìngola"],
    [12,"chambre","une chambre avec un grand lit",8,"una matrimoniale"],
    [12,"chambre","une chambre",8,"una càmera"],
    [5,"chambre","une chambre à coucher",1,"una càmera da letto"],
    [12,"chambre","une chambre avec vue",8,"una càmera con vista"],
    [12,"chambre","une chambre double",8,"una dòppia"],
    [6,"champignon","un champignon",1,"un fungo"],
    [14,"championnat","un championnat",8,"un campionato"],
    [16,"changement","un changement climatique",8,"un cambiamento climàtico"],
    [8,"changer","se changer",1,"cambiarsi"],
    [13,"chanson","une chanson",8,"una canzone"],
    [13,"chant","un chant",8,"un canto"],
    [13,"chanter","chanter",8,"cantare"],
    [13,"chanteur","un chanteur",8,"un cantante"],
    [8,"chapeau","un chapeau",1,"un cappello"],
    [13,"chapitre","un chapitre",8,"un capìtolo"],
    [6,"charcuterie","la charcuterie",1,"i salumi"],
    [12,"chargeur","un chargeur (de batterie)",8,"una caricabatteria"],
    [16,"chasser","chasser",8,"cacciare"],
    [16,"chat","un chat",8,"un gatto"],
    [1,"châtain","châtain",1,"castano"],
    [13,"chatter","chatter",8,"chattare"],
    [6,"chaud","chaud",1,"caldo"],
    [5," chaudière","une chaudière",1,"una caldàia"],
    [5,"chauffage","un chauffage",1,"un riscaldamento"],
    [12,"chauffeur","un chauffeur",8,"un autista"],
    [8,"chaussettes","les chaussettes",1,"i calzini"],
    [8,"chaussure","une chaussure",1,"una scarpa"],
    [1,"chauve","chauve",1,"calvo/pelato"],
    [10,"chef","un chef d'entreprise",1,"un imprenditore"],
    [5,"cheminée","une cheminée",1,"un caminetto"],
    [8,"chemise","une chemise",1,"una camìcia"],
    [8,"chemise","une chemise de nuit",1,"una vestàglia"],
    [16,"chêne","un chêne",8,"una quércia"],
    [9,"chercheur","un chercheur",1,"un ricercatore"],
    [16,"cheval","un cheval",8,"un cavallo"],
    [14,"cheval","monter à cheval",8,"andare a cavallo"],
    [1,"cheveux","les cheveux",1,"i capelli"],
    [3,"cheville","une cheville",1,"una cavìglia"],
    [6,"chèvre","de chèvre",1,"di capra/caprino"],
    [16,"chèvre","une chèvre",8,"una capra"],
    [16,"chien","un chien",8,"un cane"],
    [10,"chiffre","un chiffre d'affaires",1,"un fatturato/un giro d'affari"],
    [11,"chimiothérapie","une chimiothérapie",1,"una chemioterapia"],
    [12,"chips","les chips",8,"le patatine"],
    [11,"chirurgien","un chirurgien",1,"un chirurgo"],
    [12,"chocolat","un chocolat chaud",8,"una cioccolata calda"],
    [13,"choeur","un choeur",8,"un coro"],
    [10,"chômage","un chômage",1,"una disoccupazione"],
    [10,"chômeur","un chômeur",1,"un disoccupato"],
    [4,"choquant","choquant",1,"scioccante"],
    [6,"chou","un chou",1,"un càvolo"],
    [16,"chouette","une chouette",8,"una civetta"],
    [15,"ciel","un ciel",8,"un cielo"],
    [16,"cigale","une cigale",8,"una cicala"],
    [5,"ciment","le ciment",1,"un cemento"],
    [7,"cimetière","un cimetière",1,"un cimitero/un composanto"],
    [13,"cinéma","un cinéma",8,"un cìnema"],
    [13,"ciseau","un ciseau",8,"uno scalpello"],
    [6,"citron","un citron",1,"un limone"],
    [16,"citronnier","un citronnier",8,"un limone"],
    [1,"clair","clair",1,"claro"],
    [13,"clarinette","une clarinette",8,"un clarinetto"],
    [13,"clavecin","un clavecin",8,"un clavicémbalo"],
    [12,"clé","une clé",8,"una chiave"],
    [15,"climat","un climat",8,"un clima"],
    [7,"clocher","un clocher",1,"un campanile"],
    [7,"cloître","un cloître",1,"un chiostro"],
    [16,"coccinelle","une coccinelle",8,"una coccinella"],
    [16,"cochon","un cochon",8,"un maiale"],
    [3,"coiffer","se coiffer",1,"pettinarsi"],
    [10,"coiffeur","un coiffeur",1,"un parrucchiere"],
    [4,"colère","s'énerver/se mettre en colère",1,"arrabbiarsi"],
    [4,"colère","une colère",1,"una còllera"],
    [1,"colérique","colérique",1,"collérico"],
    [13,"collectionner","collectionner",8,"collezionare"],
    [9,"collège","le collège",1,"le médie"],
    [9,"collège","être au collège",1,"fare le médie"],
    [16,"colline","une colline",8,"una collina"],
    [11,"collyre","un collyre",1,"un collìrio"],
    [5,"colocataire","un colocataire",1,"un coinquilino"],
    [5,"coloré","coloré",1,"colorato"],
    [10,"commerçant","un commerçant",1,"un commerciante"],
    [16,"commerce","un commerce équitable",8,"un commercio equo-solidale"],
    [2,"compagne","une compagne",1,"una compagna"],
    [2,"compagnon","un compagnon",1,"un compagno"],
    [12,"compartiment","un compartiment",8,"uno scompartimento"],
    [12,"complet","complet",8,"completo"],
    [1,"comporter","se comporter",1,"comportarsi"],
    [13,"composer","composer",8,"comporre"],
    [11,"comprimé","un comprimé",1,"una compressa"],
    [10,"comptable","un comptable",1,"un ragioniere"],
    [10,"comptable","un expert-comptable",1,"un commercialista"],
    [12,"comptoir","un comptoir",8,"un banco"],
    [13,"concert","un concert",8,"un concerto"],
    [10,"concurrence","une concurrence",1,"una concorrenza"],
    [5,"confortable","confortable",1,"còmodo"],
    [5,"congélateur","un congélateur",1,"un congelatore"],
    [6,"congelé","congelé",1,"congelato"],
    [10,"congés","les congés",1,"le férie"],
    [16,"contaminer","contaminer",8,"contaminare"],
    [13,"conte","un conte/un récit",8,"un racconto"],
    [15,"contemporain","contemporain",8,"contemporàneo"],
    [4,"content","content",1,"contento"],
    [11,"contraception","les moyens de contraception",1,"i mezzi di contraccezione"],
    [10,"contrat","un cdi",1,"un contratto a tempo indeterminato"],
    [10,"contrat","un contrat de travail",1,"un contratto di lavoro"],
    [10,"contrat","un cdd",1,"un contratto a tempo determinato"],
    [5,"contrat","un contrat",1,"un contratto"],
    [13,"contrebasse","une contrebasse",8,"un contrabbasso"],
    [1,"coordonnée","les coordonnées (état civil)",1,"i recàpiti"],
    [5,"copropriété","une copropriété",1,"un condomìnio"],
    [16,"coq","un coq",8,"un gallo"],
    [6,"coquillage","un coquillage",1,"una conchìglia"],
    [6,"coquille","une coquille Saint-Jacques",1,"una capasanta"],
    [16,"corbeau","un corbeau",8,"un corvo"],
    [9,"corriger","corriger",1,"corréggere"],
    [1,"costaud","costaud",1,"robusto"],
    [13,"costume","les costumes",8,"i costumi"],
    [8,"costume","un costume",1,"un completo"],
    [13,"costumier","un costumier",8,"un costumista"],
    [16,"côte","une côte (mer)",8,"una costa"],
    [11,"coton","le coton/l'ouatte",1,"il cotone/l'ovatta"],
    [3,"cou","le cou",1,"il collo"],
    [15,"coucher","aller se coucher",8,"andare a dormire"],
    [3,"coude","un coude",1,"un gòmito"],
    [13,"couleur","les couleurs",8,"i colori"],
    [13,"coulisses","les coulisses",8,"le quinte"],
    [4,"coup","le coup de foudre",1,"il colpo di fùlmine"],
    [6,"couper","couper",1,"tagliare"],
    [6,"courgette","une courgette",1,"una zucchina"],
    [3,"courir","courir",1,"còrrere"],
    [9,"cours","une salle de cours",1,"un'àula"],
    [9,"cours","un cours (ensemble des leçons)",1,"un corso"],
    [9,"cours","un cours (la leçon)",1,"una lezione"],
    [14,"course","une course",8,"una corsa"],
    [8,"courses","faire les courses",1,"fare la spesa"],
    [1,"court","court",1,"corto"],
    [13,"court-métrage","un court-métrage",8,"un cortometràggio"],
    [2,"cousin","un cousin",1,"un cugino"],
    [2,"cousine","une cousine",1,"una cugina"],
    [5,"coussin","un coussin/un oreiller",1,"un cuscino"],
    [6,"couteau","un couteau",1,"un coltello"],
    [6,"couvercle","un couvercle",1,"un copérchio"],
    [15,"couvert","couvert",8,"coperto"],
    [6,"couverts","les couverts",1,"le posate"],
    [5,"couverture","une couverture",1,"una coperta"],
    [6,"crabe","un crabe",1,"un grànchio"],
    [11,"cracher","cracher",1,"sputare"],
    [9,"craie","une craie",1,"un gesso"],
    [4,"craindre","craindre",1,"temere"],
    [16,"crapaud","un crapaud",8,"un rospo"],
    [14,"crawl","le crawl",8,"lo stile lìbero"],
    [3,"crayon","un crayon",1,"una matita"],
    [9,"crèche","une crèche",1,"un asilo nido"],
    [3,"crème","une crème",1,"una crema"],
    [6,"crevette","une crevette",1,"un gamberetto"],
    [13,"critique","une critique",8,"una crìtica"],
    [13,"critique","un critique",8,"un crìtico"],
    [13,"critique","la critique (de livre, de film)",8,"la recensione"],
    [7,"croisement","un croisement",1,"un incròcio"],
    [12,"croisière","une croisière",8,"una crociera"],
    [2,"croissance","la croissance",1,"la créscita"],
    [6,"cru","cru",1,"crudo"],
    [16,"crue","une crue",8,"una piena"],
    [6,"cuillère","une petite cuillère",1,"un cucchiaino"],
    [6,"cuillère","une cuillère",1,"un cucchiàio"],
    [6,"cuire","cuire",1,"cuòcere"],
    [5,"cuisine","la cuisine (pièce)",1,"la cucina"],
    [6,"cuisiner","cuisiner",1,"cucinare"],
    [10,"cuisinier","un cuisinier",1,"un cuoco"],
    [3,"cuisse","une cuisse",1,"una còscia"],
    [12,"cuit","bien cuit",8,"ben cotto"],
    [6,"cuit","cuit",1,"cotto"],
    [12,"cuit","trop cuit (pâtes)",8,"scotto"],
    [7,"cul-de-sac","un cul-de-sac",1,"un vìcolo cieco"],
    [8,"culotte","la culotte",1,"le mutande"],
    [6,"cumin","un cumin",1,"un cumino"],
    [10,"curriculum","un cv",1,"un currìculum"],
    [5,"cuvette","une cuvette",1,"una tazza"],
    [13,"cymbales","les cymbales",8,"i piatti"],
    [16,"cyprès","un cyprès",8,"un cipresso"],
    [16,"dangereux","dangereux",8,"pericoloso"],
    [14,"danse","une danse",8,"una danza"],
    [16,"dauphin","un dauphin",8,"un delfino"],
    [6,"débarasser","débarasser (la table)",1,"sparecchiare"],
    [5,"débarras","un débarras/un cagibi",1,"uno sgabuzzino"],
    [16,"déboisement","un déboisement",8,"un disboscamento"],
    [8,"débraillé","débraillé",1,"sbracato"],
    [15,"décennie","une décennie",8,"un decénnio"],
    [16,"décharge","une décharge",8,"una discàrica"],
    [16,"déchet","les déchets",8,"i rifiuti"],
    [12,"décollage","un décollage",8,"un decollo"],
    [12,"décoller","décoller",8,"decollare"],
    [13,"décor","un décor",8,"uno scenàrio"],
    [13,"décorateur","un décorateur/un scénographe",8,"uno scenògrafo"],
    [13,"décors","les décors",8,"la scenografia"],
    [1,"défaut","un défaut",1,"un difetto"],
    [16,"dégât","un dégât",8,"un danno"],
    [12,"déguster","déguster",8,"degustare"],
    [6,"déjeuner","déjeuner (verbe)",1,"pranzare"],
    [5,"déménager","déménager",1,"traslocare"],
    [2,"demi-frère","un demi-frère",1,"un fratellastro"],
    [2,"demi-soeur","une demi-soeur",1,"una sorellastra"],
    [10,"démissionner","démissionner",1,"diméttersi/dare le dimissioni"],
    [8,"démodé","démodé",1,"fuori moda"],
    [15,"démodé","être démodé",8,"éssere fuori moda"],
    [3,"dentifrice","un dentifrice",1,"un dentifrìcio"],
    [11,"dentiste","un dentiste",1,"un dentista"],
    [12,"départ","un départ",8,"una partenza"],
    [8,"dépenser","dépenser",1,"spéndere"],
    [1,"dépensier","dépensier",1,"spendaccione"],
    [7,"déplacer","se déplacer",1,"spostarsi"],
    [16,"dépouillé","dépouillé",8,"spòglio"],
    [4,"déprimé","déprimé",1,"depresso"],
    [1,"désagréable","désagréable",1,"sgradévole"],
    [12,"descendre","descendre de la voiture",8,"scéndere della màcchina"],
    [16,"désert","un désert",8,"un deserto"],
    [16,"désertification","une désertification",8,"una desertificazione"],
    [11,"désinfectant","un désinfectant",1,"un disinfettante"],
    [4,"désirer","désirer",1,"desiderare"],
    [5,"désordonné","désordonné",1,"disordinato"],
    [12,"dessert","un dessert",8,"un dessert"],
    [7,"desservi","bien desservi",1,"collegato bene"],
    [7,"desservir","desservir (transport)",1,"collegare"],
    [13,"dessin","un dessin",8,"un disegno"],
    [13,"dessiner","dessiner",8,"disegnare"],
    [12,"destination","una destinazione/una meta",8,"un vaccino"],
    [12,"détendre","se détendre",8,"rilassarsi"],
    [16,"détruire","détruire",8,"distrùggere"],
    [16,"dévaster","dévaster",8,"devastare"],
    [16,"développement ","un développement durable",8,"uno sviluppo sostenìbile"],
    [9,"devoir","les devoirs",1,"i còmpiti"],
    [12,"digestif","un digestif",8,"un digestivo"],
    [5,"dimension","une dimension/une taille",1,"una dimensione"],
    [6,"dinde","une dinde",1,"un tacchino"],
    [6,"dîner","un dîner",1,"una cena"],
    [6,"dîner","dîner (verbe)",1,"cenare"],
    [16,"dioxyde","le dioxyde de carbone",8,"il biòssido di carbònio"],
    [9,"diplôme","un diplôme",1,"un diploma"],
    [9,"diplôme","un diplôme universitaire",1,"una làurea"],
    [9,"diplôme","passer son diplôme universitaire",1,"laurearsi"],
    [9,"diplômé","un diplômé",1,"un laureato"],
    [10,"dirigeant","un dirigeant",1,"un dirigente"],
    [7,"distributeur","un distributeur automatique",1,"un distributore automàtico"],
    [2,"divorce","un divorce",1,"un divòrzio"],
    [1,"divorcé","divorcé",1,"divorziato"],
    [2,"divorcer","divorcer",1,"divorziare"],
    [9,"doctorant","un doctorant",1,"un dottorando"],
    [9,"doctorat","un doctorat",1,"un dottorato"],
    [13,"documentaire","un documentaire",8,"un documentàrio"],
    [3,"doigt","un doigt, les doigts",1,"un dito, le dita"],
    [6,"dorade","une daurade",1,"un'orata"],
    [15,"dormir","dormir",8,"dormire"],
    [3,"dos","un dos",1,"una schiena"],
    [14,"dos","le dos crawlé",8,"il dorso"],
    [5,"douche","une douche",1,"una dòccia"],
    [15,"doux","doux (temps)",8,"mite"],
    [1,"doux","doux",1,"dolce"],
    [5,"drap","un drap, les draps",1,"un lenzuolo, le lenzuola"],
    [5,"droit","droit",1,"dritto"],
    [1,"drôle","drôle",1,"buffo"],
    [5,"dur","dur",1,"duro"],
    [12,"eau","une eau gazeuse",8,"un'acqua frizzante"],
    [16,"eau","une eau",8,"un'àcqua"],
    [12,"eau","une eau plate",8,"un'acqua naturale"],
    [8,"écharpe","une écharpe",1,"una sciarpa"],
    [9,"échouer","échouer (examen)",1,"éssere bocciato"],
    [15,"éclair","un éclair",8,"un fùlmine"],
    [15,"éclaircie","une éclaircie",8,"una schiarita"],
    [9,"école","une école",1,"una scuola"],
    [9,"écolier","un écolier",1,"uno scolaro"],
    [12,"économique","économique",8,"econòmico"],
    [16,"écorce","une écorce",8,"una cortéccia"],
    [16,"éco-système","un éco-système",8,"un ecosistema"],
    [3,"écouter","écouter",1,"ascoltare"],
    [6,"écrevisse","une écrevisse",1,"un gàmbero"],
    [13,"écrire","écrire",8,"scrìvere"],
    [13,"écrit","un écrit",8,"un scritto"],
    [13,"écrivain","un écrivain",8,"uno scrittore"],
    [16,"écume","une écume",8,"una schiuma/una spuma"],
    [16,"écureuil","un écureuil",8,"uno scoiàttolo"],
    [13,"éditeur","un éditeur",8,"un editore"],
    [9,"éducation","l'éducation nationale",1,"la pùbblica istruzione"],
    [4,"effrayer","effrayer",1,"spaventare"],
    [7,"église","une église",1,"una chiesa"],
    [1,"égoïste","égoïste",1,"egoista"],
    [1,"élancé","élancé",1,"slanciato"],
    [10,"électricien","un électricien",1,"un elettricista"],
    [9,"élève","un élève",1,"un alunno"],
    [1,"élevé","bien élevé",1,"educato"],
    [16,"éliminer","éliminer",8,"smaltire"],
    [12,"embarquement","un embarquement",8,"un imbarco"],
    [12,"embarquer","embarquer",8,"imbarcarsi"],
    [7,"embouteillage","un embouteillage",1,"un ingorgo"],
    [4,"embrasser","embrasser",1,"baciare"],
    [5,"emménager","emménager",1,"trasferirsi"],
    [4,"émouvant","émouvant",1,"commovente"],
    [10,"emploi","la place/l'emploi/le poste à pourvoir",1,"il posto"],
    [10,"emploi","pôle emploi",1,"l'uffìcio di collocamento"],
    [10,"emploi","un emploi",1,"un impiego"],
    [10,"employé","un employé",1,"un impiegato"],
    [10,"employer","employer",1,"assùmere"],
    [10,"employeur","un employeur",1,"un datore di lavoro"],
    [4,"ému","ému",1,"commosso"],
    [6,"encas","un encas",1,"uno spuntino"],
    [12,"en-cas","un en-cas",8,"uno spuntino"],
    [16,"énergie","une énergie photovoltaïque",8,"un'energia fotovoltàica"],
    [16,"énergie","une énergie éolienne",8,"un'energia eòlica"],
    [2,"enfance","une enfance",1,"un'infànzia"],
    [2,"enfant","les enfants (parenté)",1,"i figli"],
    [2,"enfant (âge)","l'enfant",1,"il bambino/il bimbo"],
    [8,"enfiler","enfiler",1,"infilare"],
    [4,"enlacer","enlacer",1,"abbracciare"],
    [8,"enlever","enlever",1,"togliere"],
    [1,"ennuyeux","ennuyeux",1,"noioso"],
    [12,"enregistrer","enregistrer les bagages",8,"registrare i bagagli"],
    [11,"enrhumé","être enrhumé",1,"éssere raffreddato"],
    [9,"enseignant","un enseignant titulaire",1,"un insegnante di ruolo"],
    [9,"enseignant","une enseignante",1,"un'insegnante"],
    [9,"enseignant","un enseignant",1,"un insegnante/un docente"],
    [9,"enseigner","enseigner",1,"insegnare"],
    [15,"ensoleillé","ensoleillé",8,"soleggiato/assolato"],
    [4,"entendre","bien s'entendre",1,"andare d'accordo"],
    [3,"entendre","entendre/sentir",1,"sentire"],
    [2,"enterrement","un enterrement",1,"un funerale"],
    [13,"entracte","un entracte",8,"un intervallo"],
    [14,"entraîner","s'entraîner",8,"allenarsi"],
    [14,"entraîneur","un entraîneur",8,"un allenatore"],
    [12,"entrée","une entrée (pâte ou soupe)",8,"un primo"],
    [10,"entreprise","une entreprise",1,"un'azienda/un'impresa"],
    [11,"entretenir","s'entretenir/se maintenir en forme",1,"mantenersi in forma"],
    [10,"entretien","un entretien d'embauche",1,"un collòquio d'assunzione"],
    [16,"environnement","un environnement",8,"un ambiente"],
    [5,"épaisseur","une épaisseur",1,"uno spessore"],
    [3,"épaule","les épaules",1,"le spalle"],
    [6,"épicé","épicé/piquant",1,"piccante"],
    [8,"épicerie","une épicerie",1,"un alimentari"],
    [6,"épices","les épices",1,"le spézie"],
    [3,"épiler","s'épiler à la cire",1,"farsi la ceretta"],
    [3,"épiler","s'épiler",1,"depilarsi"],
    [6,"épinards","les épinards",1,"gli spinaci"],
    [16,"épine","une épine",8,"una spina"],
    [6,"éplucher","éplucher",1,"pelare/sbucciare"],
    [2,"époux","les époux",1,"i còniugi"],
    [14,"équitation","une équitation",8,"un'equitazione"],
    [16,"escarpé","escarpé",8,"scosceso"],
    [14,"escrime","une escrime",8,"una scherma"],
    [6,"espadon","un espadon",1,"un pescespada"],
    [16,"espèce","une espèce en voie de disparition",8,"una spécie in via di estinzione"],
    [13,"esquisse","une esquisse/un croquis",8,"uno schizzo"],
    [13,"essai","un essai (littérature)",8,"un sàggio"],
    [8,"essayer","essayer",1,"provare"],
    [13,"essayiste","un essayiste",8,"un saggista"],
    [3,"essuyer","s'essuyer/se sécher",1,"asciugarsi"],
    [10,"esthéticien","un esthéticien",1,"un estetista"],
    [5,"étage","un étage",1,"un piano"],
    [5,"étagère","une étagère",1,"una ménsola"],
    [12,"étape","une étape",8,"una tappa"],
    [5,"état","un état des lieux",1,"un inventàrio"],
    [15,"été","un été",8,"un'estate"],
    [11,"éternuer","éternuer",1,"starnutire"],
    [8,"étiquette","une étiquette",1,"un'etichetta"],
    [15,"étouffant","étouffant/lourd",8,"afoso"],
    [4,"étourdi","étourdi",1,"frastornato"],
    [4,"étreinte","une accolade/une étreinte",1,"un abbràccio"],
    [9,"études","les études universitaires",1,"gli studi universitari"],
    [9,"étudiant","un étudiant de première année",1,"una matrìcola"],
    [9,"étudiant","un étudiant",1,"uno studente"],
    [12,"évader","s'évader",8,"svagarsi"],
    [11,"évanouir","s'évanouir",1,"svenire/pérdere i sensi"],
    [5,"évier","un évier",1,"un lavello/un lavandino"],
    [9,"examen","un examen (école)",1,"un esame/una prova"],
    [9,"examen","réussir un examen",1,"passare un esame"],
    [14,"exercice","faire de l'exercice",8,"fare ginnàstica"],
    [9,"exercice","un exercice",1,"un esercìzio"],
    [2,"ex-femme","une ex-femme",1,"un'ex-mòglie"],
    [2,"ex-mari","un ex-mari",1,"un ex-marito"],
    [13,"exposer","exposer",8,"esporre"],
    [13,"exposition","une exposition",8,"una mostra"],
    [12,"expresso","un expresso",8,"un espresso"],
    [9,"expulser","expulser",1,"espéllere"],
    [1,"extraverti","extraverti",1,"estroverso"],
    [12,"facile","facile d'accès",8,"facilmente raggiungìbile"],
    [9,"faculté","une faculté (école)",1,"una facoltà"],
    [6,"fade","fade",1,"insìpido"],
    [11,"faible","faible",1,"débole"],
    [4,"faire","faire l'amour",1,"fare l'amore"],
    [2,"famille","la famille monoparentale",1,"la famìglia monoparentale"],
    [16,"faner","faner/se flétrir",8,"appassire/sfiorire"],
    [6,"farine","une farine",1,"una farina"],
    [12,"fatiguer","se fatiguer",8,"stancarsi"],
    [14,"faute","une faute",8,"un fallo"],
    [5,"fauteuil","un fauteuil",1,"una poltrona"],
    [1,"femme","une femme",1,"una donna"],
    [2,"femme","la femme (épouse)",1,"la mòglie"],
    [5,"fenêtre","une fenêtre",1,"una finestra"],
    [5,"fer","un fer à repasser",1,"un ferro da stiro"],
    [5,"fer","le fer",1,"il ferro"],
    [12,"fermé","fermé",8,"chiuso"],
    [12,"ferry","un ferry",8,"un traghetto"],
    [3,"fesse","les fesses",1,"il sedere"],
    [16,"feu","un feu",8,"un fuoco"],
    [7,"feu","un feu de circulation",1,"un semàforo"],
    [16,"feuille","une feuille (arbre)",8,"una fòglia"],
    [9,"feuille","une feuille (papier)",1,"un fòglio"],
    [9,"feutre","un feutre (écriture)",1,"un pennarello"],
    [2,"fiancé","un fiancé",1,"un fidanzato"],
    [2,"fiancée","une fiancée",1,"una fidanzata"],
    [2,"fiancer","se fiancer",1,"fidanzarsi"],
    [11,"fièvre","une fièvre",1,"una febbre"],
    [13,"figurant","un figurant",8,"una comparsa"],
    [2,"fille","une vieille fille",1,"una zitella"],
    [2,"fille","la fille/l'enfant",1,"la fìglia"],
    [13,"film","un film",8,"un film"],
    [13,"film","tourner un film",8,"girare un film"],
    [12,"filmer","filmer",8,"fare delle riprese/ripréndere"],
    [2,"fils","le fils/l'enfant",1,"il fìglio"],
    [10,"firme","une firme",1,"una ditta"],
    [16,"flaque","une flaque",8,"una pozzànghera"],
    [16,"fleur","une fleur",8,"un fiore"],
    [16,"fleurir","fleurir",8,"fiorire"],
    [16,"fleuve","un fleuve",8,"un fiume"],
    [10,"flexible","flexible",1,"flessìbile"],
    [15,"flocon","un flocon",8,"un fiocco"],
    [13,"flûte","une flûte",8,"un flàuto"],
    [1,"foncé","foncé",1,"scuro"],
    [10,"fonctionnaire","un fonctionnaire",1,"un impiegato statale"],
    [3,"fond de teint","un fond de teint",1,"un fondotinta"],
    [6,"fondu","fondu",1,"fuso"],
    [7,"fontaine","une fontaine",1,"una fontana"],
    [14,"football","le football",8,"il càlcio"],
    [16,"forêt","une forêt",8,"una foresta"],
    [5,"four","un (four à) microonde",1,"un microonde"],
    [5,"four","un four",1,"un forno"],
    [6,"fourchette","une fourchette",1,"una forchetta"],
    [16,"fourmi","une fourmi",8,"una formica"],
    [11,"fragile","fragile",1,"fragile"],
    [6,"frais","frais",1,"fresco"],
    [6,"fraise","une fraise",1,"una fràgola"],
    [6,"framboise","une framboise",1,"un lampone"],
    [4,"frayeur","une frayeur",1,"uno spavento"],
    [2,"frère","un frère",1,"un fratello"],
    [5,"frigidaire","un frigidaire",1,"un frigorìfero"],
    [6,"frire","frire",1,"frìggere"],
    [15,"froid","un froid",8,"un freddo"],
    [6,"froid","froid",1,"freddo"],
    [6,"fromage","un fromage de vache à pâte demi-dure",1,"una fontina"],
    [6,"fromage","un fromage frais de buflonne",1,"una mozzarella"],
    [6,"fromage","un fromage de brebis à pâte dure",1,"un pecorino"],
    [6,"fromage","un fromage",1,"un formàggio"],
    [6,"fromage","un fromage de vache à pâte fraîche",1,"una ricotta"],
    [3,"front","un front",1,"un fronte"],
    [6,"fruit","les fruits de mer",1,"i frutti di mare"],
    [6,"fruits","les fruits des bois",1,"i frutti di bosco"],
    [6,"fruits","les fruits",1,"la frutta"],
    [15,"futur","un futur",8,"un futuro"],
    [10,"gagner","gagner",1,"guadagnare"],
    [14,"gagner","gagner (la partie)",8,"vìncere"],
    [13,"galerie","une galerie d'art",8,"una galleria d'arte"],
    [16,"galet","un galet",8,"un sasso"],
    [8,"gant","les gants",1,"i guanti"],
    [10,"garagiste","un garagiste/un mécanicien",1,"un meccànico"],
    [2,"garçon","un vieux garçon",1,"uno scàpolo"],
    [2,"garde","une garde alternée",1,"un affidamento alternato"],
    [14,"gardien","un gardien de but",8,"un portiere"],
    [9,"gardien","un gardien",1,"un bidello"],
    [12,"gare","une gare routière",8,"una stazione degli àutobus"],
    [12,"gare","une gare",8,"una stazione"],
    [7,"garer","se garer",1,"parcheggiare"],
    [16,"gaspiller","gaspiller",8,"sprecare"],
    [12,"gâteau","un gâteau",8,"un dolce"],
    [16,"gazon","un gazon",8,"un'erba/un prato"],
    [3,"gel","le gel douche/le bain moussant",1,"il bagnoschiuma"],
    [7,"gendarme","les gendarmes",1,"i carabinieri"],
    [2,"gendre","un gendre",1,"un género"],
    [1,"généreux","généreux",1,"generoso"],
    [3,"genou","se mettre à genoux",1,"inginocchiarsi"],
    [3,"genou","un genou",1,"un ginòcchio"],
    [16,"germer","germer",8,"germogliare"],
    [12,"gîte","un gîte rural",8,"un agriturismo"],
    [15,"glace","une glace",8,"un ghiàccio"],
    [16,"glace","la fonte des glaces",8,"lo scioglimento dei ghiacciai"],
    [9,"gomme","une gomme (école)",1,"una gomma da cancellare"],
    [6,"gousse","une gousse",1,"uno spìcchio"],
    [3,"goût","un goût",1,"un gusto"],
    [6,"goûter","un goûter (repas)",1,"una merenda"],
    [12,"goûter","goûter",8,"assaggiare"],
    [16,"graine","une graine",8,"un seme"],
    [1,"grand","grand (taille)",1,"alto"],
    [2,"grandir","grandir",1,"créscere"],
    [2,"grand-mère","une grand-mère",1,"una nonna"],
    [2,"grand-père","un grand-père",1,"un nonno"],
    [10,"graphiste","un graphiste",1,"un gràfico"],
    [6,"grappe","une grappe",1,"un gràppolo"],
    [13,"gravure","une gravure",8,"un'incisione"],
    [15,"grêle","une grêle",8,"una gràndine"],
    [15,"grêler","grêler",8,"grandinare"],
    [5,"grenier","un grenier",1,"una soffitta"],
    [16,"grenouille","une grenouille",8,"una rana"],
    [10,"grève","une grève",1,"uno sciòpero"],
    [10,"gréviste","un gréviste",1,"uno scioperante"],
    [12,"grignoter","grignoter",8,"mangiucchiare/spiluccare"],
    [12,"grill","au grill/à la plancha",8,"alla piastra"],
    [6,"grillé","grillé (pain)",1,"tostato"],
    [6,"grillé","grillé (viande)",1,"grigliato"],
    [11,"grippe","une grippe",1,"un'influenza"],
    [15,"gris","gris",8,"grigio"],
    [1,"gros","gros",1,"grasso"],
    [1,"grossir","grossir",1,"ingrassare"],
    [6,"gruyère","un gruyère",1,"una groviera"],
    [16,"guêpe","une guêpe",8,"una vespa"],
    [11,"guérir","guérir",1,"guarire"],
    [12,"guichet","un guichet",8,"uno sportello"],
    [7,"guichet","un guichet automatique bancaire",1,"un bancomat"],
    [12,"guide","un guide",8,"una guida"],
    [13,"guitarre","une guitarre",8,"una chitarra"],
    [11,"gynécologue","un gynécologue",1,"un ginecòlogo"],
    [8,"habit","un habit/une robe",1,"un vestito"],
    [6,"hacher","hacher",1,"tritare"],
    [16,"haie","une haie",8,"una siepe"],
    [4,"haine","une haine",1,"un òdio"],
    [4,"haïr","haïr",1,"odiare"],
    [5,"hall","un hall",1,"un androne"],
    [14,"handball","le handball",8,"la pallamano"],
    [10,"harcèlement","le harcèlement moral",1,"il mobbing"],
    [6,"haricot","un haricot vert",1,"un fagiolino"],
    [6,"haricot","un haricot",1,"un fagiolo"],
    [13,"harpe","une harpe",8,"un'arpa"],
    [5,"hauteur","une hauteur",1,"un'altezza"],
    [16,"hennir","hennir",8,"nitrire"],
    [6,"herbes","les fines herbes",1,"le erbe aromàtiche"],
    [15,"heure","il est cinq heures dix",8,"sono le cinque e dieci"],
    [15,"heure","dans trois minutes, il sera six heures",8,"màncano tre minuti alle sei"],
    [15,"heure","il est huit heures moins cinq",8,"sono le venti meno cinque"],
    [15,"heure","il est deux heures",8,"sono le due"],
    [15,"heure","il est une heure",8,"è l'una"],
    [15,"heure","quelle heure est-il ?",8,"che ora è?/che ore sono?"],
    [15,"heure","une heure",8,"un'ora"],
    [10,"heure","les heures supplémentaires",1,"gli straordinari"],
    [4,"heureux","heureux",1,"felice"],
    [16,"hibou","un hibou",8,"un gufo"],
    [15,"hiver","un hiver",8,"un inverno"],
    [6,"homard","un homard",1,"un àstice"],
    [1,"homme","un homme",1,"un uomo"],
    [11,"hôpital","un hôpital",1,"un ospedale"],
    [12,"horaire","un horaire",8,"un oràrio"],
    [11,"hormones","les hormones",1,"gli ormoni"],
    [12,"hors d'oeuvre","un hors d'oeuvre/une entrée",8,"un antipasto"],
    [11,"hospitaliser","hospitaliser",1,"ricoverare"],
    [12,"hôtel","un hôtel",8,"un albergo"],
    [12,"hôtesse","une hôtesse",8,"un'hostess"],
    [6,"huile","une huile",1,"un òlio"],
    [6,"huître","une huître",1,"un'òstrica"],
    [15,"humide","humide",8,"ùmido"],
    [1,"hypocrite","hypocrite",1,"ipòcrita"],
    [4,"illusion","se faire des illusions",1,"illùdersi"],
    [5,"immeuble","un immeuble",1,"un palazzo"],
    [4,"inattendu","inattendu",1,"inatteso"],
    [13,"inauguration","une inauguration",8,"un'inaugurazione"],
    [4,"incroyable","incroyable",1,"incredìbile"],
    [9,"indiscipliné","indiscipliné",1,"dìscolo"],
    [1,"individu","un individu",1,"un indivìduo"],
    [11,"infarctus","un infarctus",1,"un infarto"],
    [10,"infirmier","un infirmier",1,"un infermiere"],
    [10,"informaticien","un informaticien",1,"un informàtico"],
    [10,"ingénieur","un ingénieur",1,"un ingegnere"],
    [16,"inoffensif","inoffensif",8,"inoffensivo"],
    [16,"inondation","une inondation",8,"un'inondazione"],
    [4,"inquiet","inquiet/agité",1,"inquieto"],
    [4,"inquiéter","s'inquiéter",1,"preoccuparsi"],
    [4,"inquiétude","une inquiétude",1,"un'inquietùdine"],
    [12,"insipide","insipide/fade",8,"insìpido"],
    [4,"inspirer","inspirer qqch à qqn",1,"incùtere qualcosa a qualcuno"],
    [13,"instrument","un instrument (musical)",8,"uno strumento"],
    [10,"intérimaire","un intérimaire",1,"un'interinale"],
    [9,"interroger","interroger",1,"interrogare"],
    [4,"intimidé","être intimidé par",1,"avere soggezione di"],
    [13,"intituler","intituler",8,"intitolare"],
    [1,"intolérant","intolérant/intransigeant",1,"insofferente"],
    [1,"introverti","introverti",1,"introverso"],
    [12,"itinéraire","un itinéraire",8,"un itinéràrio"],
    [3,"jambe","une jambe",1,"una gamba"],
    [6,"jambon","un jambon",1,"un prosciutto"],
    [16,"jardin","un jardin",8,"un giardino"],
    [7,"jardin","un jardin public",1,"un giardino pùbblico"],
    [13,"jardinage","un jardinage",8,"un giardinàggio"],
    [5,"jaune","jaune",1,"giallo"],
    [13,"jeu","les jeux de société",8,"i giochi di società"],
    [13,"jeu","les jeux vidéos",8,"i videogiochi"],
    [1,"jeune","jeune",1,"giòvane"],
    [14,"jogging","faire du jogging",8,"fare jogging"],
    [4,"joie","une joie",1,"una giòia"],
    [1,"joli","joli/mignon",1,"carino"],
    [3,"joue","une joue, les joues",1,"una guància, le guance"],
    [13,"jouer","jouer (instrument)",8,"suonare"],
    [10,"jour","un jour férié",1,"un giorno festivo"],
    [15,"jour","un jour",8,"un giorno"],
    [10,"jour","un jour ouvrable",1,"un giorno feriale"],
    [15,"journée","une journée",8,"una giornata"],
    [1,"joyeux","joyeux",1,"allegro"],
    [14,"judo","le judo",8,"il judo"],
    [10,"juge","un juge",1,"un giùdice"],
    [8,"jupe","une jupe",1,"una gonna"],
    [12,"jus","un jus d'oranges pressées",8,"una spremuta d'arància"],
    [6,"jus","un jus de fruit",1,"un succo di frutta"],
    [14,"karaté","le karaté",8,"il karate"],
    [11,"kinésithérapeute","un kinésithérapeute",1,"un fisioterapista"],
    [8,"kiosque","un kiosque à journaux",1,"un'edìcola"],
    [16,"lac","un lac",8,"un lago"],
    [6,"lait","le lait",1,"il latte"],
    [5,"lampe","une lampe",1,"una làmpada"],
    [14,"lancer","lancer",8,"tirare/lanciare"],
    [6,"langouste","une langouste",1,"un'aragosta"],
    [3,"langue","une langue",1,"una lìngua"],
    [16,"lapin","un lapin",8,"un conìglio"],
    [8,"large","large",1,"largo"],
    [5,"largeur","une largeur",1,"una larghezza"],
    [4,"larme","une larme",1,"una làcrima"],
    [6,"laurier","un laurier",1,"un alloro"],
    [5,"lavabo","un lavabo",1,"un lavabo/un lavandino"],
    [16,"lavande","une lavande",8,"una lavanda"],
    [3,"laver","se laver",1,"lavarsi"],
    [5,"lave-vaisselle","un lave-vaisselle",1,"una lavastovìglie"],
    [13,"lecteur","un lecteur",8,"un lettore"],
    [5,"léger","léger",1,"leggero"],
    [6,"légumes","les légumes",1,"la verdura"],
    [10,"lettre","une lettre de motivation",1,"una léttera di presentazione/una léttera di motivazione"],
    [3,"lever","se lever",1,"alzarsi"],
    [3,"lèvre","une lèvre, les lèvres",1,"un labbro, le labbra"],
    [16,"lézard","un lézard",8,"una lucértola"],
    [13,"libraire","un libraire",8,"un libràio"],
    [9,"licence","une licence",1,"una làurea breve"],
    [10,"licencier","licencier",1,"licenziare"],
    [5,"liège","le liège",1,"il sùghero"],
    [16,"lierre","un lierre",8,"un'édera"],
    [16,"lièvre","un lièvre",8,"una lepre"],
    [13,"ligne","une ligne (écriture)",8,"una riga"],
    [12,"ligne","la ligne",8,"la lìnea"],
    [13,"lire","lire",8,"léggere"],
    [5,"lit","un lit",1,"un letto"],
    [13,"livre","un livre de poche",8,"un libro tascàbile"],
    [9,"livre","un livre",1,"un libro"],
    [5,"locataire","un locataire",1,"un inquilino"],
    [1,"long","long",1,"lungo"],
    [5,"longueur","une longueur",1,"una lunghezza"],
    [6,"louche","une louche",1,"un méstolo"],
    [12,"louer","louer (une voiture)",8,"noleggiare"],
    [5,"louer","louer",1,"affittare"],
    [12,"louer","louer (un appartement)",8,"affittare"],
    [16,"loup","un loup",8,"un lupo"],
    [5,"lourd","lourd",1,"pesante"],
    [5,"loyer","un loyer",1,"un affitto"],
    [12,"luxueux","luxueux",8,"lussuoso"],
    [9,"lycée","un lycée",1,"un liceo"],
    [9,"lycée","être au lycée",1,"fare le superiori"],
    [9,"lycée","un lycée professionnel",1,"un istituto técnico"],
    [16,"lys","un lys",8,"un gìglio"],
    [5,"machine","une machine à laver",1,"una lavatrice"],
    [10,"maçon","un maçon",1,"un muratore"],
    [8,"magasin","un magasin",1,"un negòzio"],
    [8,"magasin","le magasin de chaussures",1,"il negòzio di scarpe"],
    [8,"magasin","le magasin de vêtements",1,"il negòzio di abbigliamento"],
    [1,"maigre","maigre",1,"magro"],
    [1,"maigrir","maigrir",1,"dimagrire"],
    [14,"maillot","un maillot",8,"una màglia"],
    [3,"main","une main, les mains",1,"una mano, le mani"],
    [7,"mairie","une mairie",1,"un municìpio"],
    [12,"maison","fait maison",8,"fatto in casa"],
    [5,"maison","la maison",1,"la casa"],
    [9,"maître","un maître",1,"un maestro"],
    [11,"mal","avoir mal au ventre",1,"avere mal di pància"],
    [11,"maladie","une maladie",1,"una malattia"],
    [4,"malheur","un malheur (état)",1,"un'infelicità"],
    [2,"maman","une maman",1,"una mamma"],
    [8,"manche","à manches courtes",1,"a màniche corte"],
    [8,"manche","à manches longues",1,"a màniche lunghe"],
    [1,"manie","une manie",1,"una mania"],
    [8,"manteau","un manteau",1,"un cappotto"],
    [3,"maquillage","un maquillage",1,"un trucco"],
    [3,"maquiller","se maquiller",1,"truccarsi"],
    [5,"marbre","un marbre",1,"un marmo"],
    [8,"marché","un marché",1,"un mercato"],
    [3,"marcher","marcher",1,"camminare"],
    [16,"mare","une mare",8,"uno stagno"],
    [16,"marée","une marée noire",8,"una marea nera"],
    [2,"mari","un mari",1,"un marito"],
    [2,"mariage","un mariage",1,"un matrimònio"],
    [2,"marié","les mariés",1,"gli sposi"],
    [1,"marié","marié",1,"sposato/coniugato"],
    [2,"marier","se marier",1,"sposarsi"],
    [14,"marquer","marquer (un but)",8,"segnare"],
    [5,"marron","marron",1,"marrone"],
    [14,"martial","les arts martiaux",8,"le arti marziali"],
    [3,"mascara","un mascara",1,"un mascara/un rimmel"],
    [11,"massage","un massage",1,"un massàggio"],
    [9,"master","un master",1,"una specialìstica/un master"],
    [14,"match","faire match nul",8,"pareggiare"],
    [14,"match","un match",8,"una partita"],
    [5,"matelas","un matelas",1,"un materasso"],
    [9,"maternelle","une maternelle (école)",1,"un asilo/una scuola materna"],
    [15,"matin","un matin",8,"una mattina/un mattino"],
    [15,"matinée","une matinée",8,"una mattinata"],
    [6,"mayonnaise","une mayonnaise",1,"una maionese"],
    [10,"médecin","un médecin",1,"un médico"],
    [11,"médicament","un médicament",1,"una medicina/un fàrmaco"],
    [4,"mélancolie","une mélancolie",1,"una malinconia"],
    [6,"mélanger","mélanger",1,"mescolare"],
    [9,"mémoire","un mémoire de master",1,"una tesi di làurea"],
    [9,"mémoire","soutenir son mémoire/sa thèse",1,"discùtere la tesi"],
    [16,"menace","une menace",8,"una minàccia"],
    [1,"menteur","menteur",1,"bugiardo"],
    [3,"menton","un menton",1,"un mento"],
    [12,"menu","un menu/un carte",8,"un menù"],
    [4,"mépris","le mépris",1,"il disprezzo"],
    [16,"mer","une mer",8,"un mare"],
    [2,"mère","une mère",1,"una madre"],
    [5,"mesure","une mesure",1,"una misura"],
    [5,"métal","un métal",1,"un metallo"],
    [15,"météo","le bulletin météo",8,"il méteo/le previsioni del tempo"],
    [12,"métro","un métro",8,"una metro"],
    [13,"metteur","un metteur en scène",8,"un regista"],
    [6,"mettre","mettre la table",1,"apparecchiare"],
    [5,"meubler","meubler/décorer",1,"arredare"],
    [5,"mezzanine","une mezzanine/une mansarde",1,"una mansarda"],
    [16,"miauler","miauler",8,"miagolare"],
    [15,"midi","il est midi",8,"è mezzogiorno"],
    [10,"militaire","un militaire",1,"un militare"],
    [16,"mimosa","un mimosa",8,"una mimosa"],
    [1,"mince","mince",1,"snello"],
    [15,"minute","une minute",8,"un minuto"],
    [5,"miroir","un miroir",1,"uno spécchio"],
    [16,"mobiliser","se mobiliser",8,"mobilitarsi"],
    [1,"moche","moche",1,"brutto"],
    [15,"mode","être à la mode",8,"andare di moda"],
    [13,"modélisme","le modélisme",8,"il modellismo"],
    [15,"moderne","moderne",8,"moderno"],
    [16,"moineau","un moineau",8,"un pàssero"],
    [15,"mois","un mois",8,"un mese"],
    [10,"mois","un treizième mois",1,"una tredicésima"],
    [3,"mollet","un mollet",1,"un polpàccio"],
    [16,"mont","un mont",8,"un monte"],
    [16,"montagne","une montagne",8,"una montagna"],
    [12,"monter","monter de la voiture",8,"salire della màcchina"],
    [13,"morceau","un morceau",8,"un brano"],
    [6,"morue","une morue (salée et séchée)",1,"un baccalà"],
    [13,"mot","les mots croisés",8,"le parole crociate"],
    [5,"mou","mou/doux/moelleux",1,"mòrbido"],
    [16,"mouche","une mouche",8,"una mosca"],
    [11,"moucher","se moucher",1,"soffiarsi il naso"],
    [16,"mouette","une mouette",8,"un gabbiano"],
    [15,"mouiller","se mouiller",8,"bagnarsi"],
    [8,"moulant","moulant",1,"attillato/aderente"],
    [6,"moule","une moule",1,"una cozza"],
    [2,"mourir","mourir",1,"morire"],
    [3,"mousse","une mousse à raser",1,"una schiuma da barba"],
    [12,"mousseux","un mousseux",8,"uno spumante"],
    [12,"mousseux","un vin blanc mousseux de Trévise",8,"un prosecco"],
    [1,"moustache","la moustache",1,"i baffi"],
    [16,"moustique","un moustique",8,"una zanzara"],
    [6,"moutarde","une moutarde",1,"una sénape"],
    [16,"mouton","un mouton",8,"un montone"],
    [9,"moyenne","la moyenne",1,"la média"],
    [5,"mur","le mur (intérieur)",1,"la parete"],
    [6,"mûr","mûr",1,"maturo"],
    [1,"musclé","musclé",1,"muscoloso"],
    [7,"musée","un musée",1,"un museo"],
    [13,"musicien","un musicien",8,"un musicista"],
    [13,"musique","écouter de la musique",8,"ascoltare mùsica"],
    [10,"mutation","une mutation",1,"un trasferimento"],
    [6,"myrtille","une myrtille",1,"un mirtillo"],
    [1,"naissance","un lieu de naissance",1,"un luogo di nàscita"],
    [1,"naissance","né à",1,"nato a"],
    [1,"naissance","une date de naissance",1,"una data di nàscita"],
    [2,"naissance","une naissance",1,"una nàscita"],
    [6,"nappe","une nappe",1,"una tovàglia"],
    [14,"natation","la natation",8,"il nuoto"],
    [12,"navette","une navette",8,"una navetta"],
    [10,"négociations","les négociations",1,"le trattative"],
    [10,"négocier","négocier",1,"negoziare"],
    [15,"neige","une neige",8,"una neve"],
    [15,"neiger","neiger",8,"nevicare"],
    [5,"nettoyer","nettoyer",1,"pulire"],
    [2,"neveu","un neveu/un petit-fils",1,"un nipote"],
    [3,"nez","un nez",1,"un naso"],
    [2,"nièce","une nièce/une petite-fille",1,"una nipote"],
    [2,"noces","les noces",1,"le nozze"],
    [16,"nocif","nocif",8,"nocivo"],
    [1,"noir","noir",1,"nero"],
    [1,"nom","un nom de famille",1,"un cognome"],
    [4,"nostalgie","une nostalgie",1,"una nostalgia"],
    [10,"notaire","un notaire",1,"un notàio"],
    [9,"note","une note (école)",1,"un voto"],
    [13,"note","une note",8,"una nota"],
    [13,"note","une fausse note",8,"una stecca"],
    [12,"note","une note (facture)",8,"una ricevuta/una fattura"],
    [9,"note","mettre une note",1,"dare un voto"],
    [6,"nourriture","la nourriture",1,"il cibo"],
    [2,"nouveau-né","un nouveau-né",1,"un neonato"],
    [13,"nouvelle","une nouvelle",8,"una novella"],
    [15,"nuage","un nuage",8,"una nùvola/una nube"],
    [15,"nuageux","nuageux",8,"nuvoloso"],
    [16,"nucléaire","nucléaire",8,"nucleare"],
    [15,"nuit","une nuit",8,"una notte"],
    [3,"odorat","un odorat",1,"un olfatto"],
    [1,"oeil","un oeil, les yeux",1,"un òcchio, gli occhi"],
    [16,"oeillet","un oeillet",8,"un garòfano"],
    [6,"oeuf","un oeuf, les oeufs",1,"un uovo, le uova"],
    [7,"office","un office du tourisme",1,"un uffìcio del turismo"],
    [10,"offre","une offre d'emploi",1,"un'offerta di lavoro"],
    [6,"oignon","un oignon",1,"una cipolla"],
    [16,"oiseau","un oiseau",8,"un uccelo"],
    [16,"olivier","un olivier",8,"un ulivo"],
    [2,"oncle","un oncle",1,"uno zio"],
    [11,"ophtalmologue","un ophtalmologue",1,"un oftalmòlogo"],
    [1,"optimiste","optimiste",1,"ottimista"],
    [15,"orage","un orage",8,"un temporale"],
    [6,"orange","une orange",1,"un'arància"],
    [5,"orange","orange",1,"aràncio"],
    [16,"oranger","un oranger",8,"un aràncio"],
    [11,"ordonnance","une ordonnance",1,"una ricetta médica"],
    [3,"oreille","une oreille, les oreilles",1,"un orécchio, le orécchie"],
    [5,"oreiller","un oreiller",1,"un guanciale"],
    [13,"orgue","un orgue",8,"un òrgano"],
    [6,"origan","un origan",1,"un orìgano"],
    [16,"orme","un orme",8,"un olmo"],
    [5,"osier","un osier",1,"un vìmini"],
    [11,"ostéopathe","un ostéopathe",1,"un osteòpata"],
    [3,"ouïe","une ouïe (audition)",1,"un udito"],
    [15,"ouragan","un ouragan",8,"un uragano"],
    [6,"oursin","un oursin",1,"un rìccio di mare"],
    [12,"ouvert","ouvert",8,"aperto"],
    [6,"ouvre-boîte","un ouvre-boîte",1,"un apriscàtole"],
    [6,"ouvre-bouteille","un ouvre-bouteille",1,"un apribottìglie"],
    [10,"ouvrier","un ouvrier",1,"un operàio"],
    [16,"ozone","une couche d'ozone",8,"uno strato di ozono"],
    [10,"paie","une paie",1,"una busta paga"],
    [6,"pain","un pain",1,"un pane"],
    [13,"palette","une palette",8,"una tavolozza"],
    [5,"palier","un palier",1,"un pianeròttolo"],
    [6,"palourde","une palourde",1,"una vòngola"],
    [6,"pané","pané",1,"impanato/panato"],
    [16,"panorama","un panorama",8,"un panorama"],
    [11,"pansement","un pansement",1,"un cerotto"],
    [11,"pansement","faire un pansement",1,"medicare una ferita"],
    [8,"pantoufle","une pantoufle",1,"una ciabatta"],
    [2,"papa","un papa",1,"un papà/un babbo"],
    [1,"papier","les papiers (état civil)",1,"i documenti"],
    [16,"papillon","un papillon",8,"una farfalla"],
    [14,"papillon","le papillon",8,"la farfalla"],
    [13,"paragraphe","un paragraphe",8,"un paràgrafo"],
    [7,"parc","un parc",1,"un parco"],
    [2,"parent","les parents",1,"i genitori"],
    [6,"parmesan","le parmesan",1,"il parmigiano"],
    [10,"partenaire","les partenaires sociaux",1,"le parti sociali"],
    [16,"parterre","un parterre",8,"un'aiuola"],
    [13,"parterre","un parterre (spectacle)",8,"una platea"],
    [13,"partition","une partition",8,"uno spartito"],
    [7,"passage","le passage clouté",1,"le strisce/le strisce pedonale"],
    [7,"passant","un passant",1,"un passante"],
    [15,"passé","un passé",8,"un passato"],
    [1,"passeport","un passeport",1,"un passaporto"],
    [12,"passer","passer la nuit",8,"pernottare"],
    [6,"passoire","une passoire",1,"uno scolapasta"],
    [6,"passoire","une petite passoire",1,"un colino"],
    [13,"pastel","les pastels",8,"i pastelli"],
    [6,"pastèque","une pastèque",1,"un'angùria/un cocòmero"],
    [7,"pâté","un pâté de maisons",1,"un isolato"],
    [6,"pâtes","les pâtes",1,"la pasta"],
    [14,"patinage","un patinage",8,"un pattinàggio"],
    [10,"patron","un patron",1,"un capo/un titolare"],
    [5,"pavillon","un pavillon (habitation)",1,"un villino"],
    [12,"payer","payer la note",8,"pagare il conto"],
    [16,"paysage","un paysage",8,"un paesàggio"],
    [10,"paysan","un paysan",1,"un contadino"],
    [3,"peau","une peau",1,"una pelle"],
    [16,"pêcher","pêcher (du poisson)",8,"pescare"],
    [3,"peigne","un peigne",1,"un péttine"],
    [3,"peignoir","un peignoir",1,"un accappatòio"],
    [13,"peindre","peindre",8,"dipìngere"],
    [13,"peintre","un peintre",8,"un pittore"],
    [13,"peinture","une peinture (activité)",8,"una pittura"],
    [13,"peinture","une peinture à l'huile",8,"una pittura ad òlio"],
    [13,"peinture","une peinture (objet)",8,"un dipinto"],
    [7,"pelouse","une pelouse/un pré",1,"un prato"],
    [14,"penalty","un penalty",8,"un rigore"],
    [5,"penderie","une penderie",1,"una guardaroba"],
    [2,"pension","la pension alimentaire",1,"gli alimenti"],
    [12,"pension","une pension complète",8,"una pensione completa"],
    [12,"pension","une demi-pension",8,"una mezza pensione"],
    [12,"pension","une pension",8,"una pensione"],
    [14,"perdre","perdre",8,"pérdere"],
    [2,"père","un père",1,"un padre"],
    [10,"période","une période d'essai",1,"un perìodo di prova"],
    [12,"permis","un permis de séjour",8,"un permesso di soggiorno"],
    [6,"persil","un persil",1,"un prezzémolo"],
    [10,"personnel","le personnel",1,"il personale"],
    [1,"peser","peser",1,"pesare"],
    [1,"pessimiste","pessimiste",1,"pessimista"],
    [16,"pesticide","les pesticides",8,"i pesticidi"],
    [16,"pétale","un pétale",8,"un pétalo"],
    [1,"petit","petit (taille)",1,"basso"],
    [6,"petit-déjeuner","un petit-déjeuner",1,"una prima colazione/una colazione"],
    [4,"peur","une peur",1,"una paura"],
    [4,"peur","avoir peur",1,"avere paura"],
    [10,"pharmacien","un pharmacien",1,"un farmacista"],
    [12,"photo","prendre une photo",8,"scattare una foto"],
    [12,"photo","un appareil photo",8,"una macchinetta fotogràfica"],
    [13,"piano","un piano",8,"un pianoforte"],
    [3,"pied","un pied",1,"un piede"],
    [7,"piéton","un piéton",1,"un pedone"],
    [16,"pigeon","un pigeon",8,"un piccione"],
    [11,"pilule","une pilule",1,"una pìllola"],
    [6,"piment","un piment",1,"un peperoncino"],
    [16,"pin","un pin",8,"un pino"],
    [3,"pince","une pince à épiler",1,"una pinzetta"],
    [13,"pinceau","un pinceau",8,"un pennello"],
    [6,"pincée","une pincée",1,"un pìzzico"],
    [11,"piqûre","une piqûre",1,"un'iniezione"],
    [16,"pistil","un pistil",8,"un pistillo"],
    [10,"piston","un piston (travail)",1,"una raccomandazione"],
    [12,"pizza","une pizza à la coupe",8,"una pizza al tàglio"],
    [12,"place","une place de parking",8,"un posto màcchina"],
    [12,"place","une place (pour s'asseoir)",8,"un posto"],
    [7,"place","une place",1,"una piazza"],
    [5,"plafond","un plafond",1,"un soffito"],
    [16,"plage","une plage",8,"una spiàggia"],
    [16,"plaine","une plaine",8,"una pianura"],
    [4,"plaire","plaire/aimer",1,"piacere"],
    [12,"plan","un plan (de la ville)",8,"una piantina"],
    [7,"plan","un plan",1,"una piantina"],
    [5,"plancher","un plancher/un grenier",1,"un solàio"],
    [16,"planète","une planète",8,"una pianeta"],
    [16,"plante","une plante",8,"una pianta"],
    [12,"plat","un plat à emporter",8,"un cibo da asporto"],
    [12,"plat","un plat (menu)",8,"un piatto"],
    [12,"plat","un plat de résistance",8,"un secondo"],
    [6,"plateau","un plateau (table)",1,"un vassòio"],
    [16,"plateau","un plateau",8,"un altopiano"],
    [11,"plâtre","un plâtre",1,"un gesso"],
    [4,"pleurer","pleurer",1,"piàngere"],
    [15,"pleuvoir","pleuvoir",8,"piòvere"],
    [10,"plombier","un plombier",1,"un idràulico"],
    [14,"plonger","plonger",8,"tuffarsi"],
    [15,"pluie","une pluie",8,"una piòggia"],
    [16,"pluies","les pluies acides",8,"le piogge àcide"],
    [6,"poële","une poëlle",1,"una padella"],
    [13,"poésie","une poésie",8,"una poesia"],
    [13,"poète","un poète",8,"un poeta"],
    [1,"poids","un poids",1,"un peso"],
    [3,"poignet","un poignet",1,"un polso"],
    [1,"poilu","poilu",1,"peloso"],
    [14,"point","un point",8,"un punto"],
    [5,"pointe","une pointe",1,"una punta"],
    [6,"poire","une poire",1,"una pera"],
    [16,"poirier","un poirier",8,"un pero"],
    [6,"pois","un petit pois",1,"un pisello"],
    [6,"pois","un pois chiche",1,"un ceco"],
    [6,"poisson","un poisson",1,"un pesce"],
    [3,"poitrine","une poitrine",1,"un petto"],
    [6,"poitrine","la poitrine/les lardons",1,"la pancetta"],
    [6,"poivre","le poivre",1,"il pepe"],
    [6,"poivron","un poivron",1,"un peperone"],
    [7,"police","une police",1,"una polizia"],
    [10,"policier","un policier",1,"un poliziotto"],
    [16,"pollué","pollué",8,"inquinato"],
    [16,"pollution","une pollution",8,"un inquinamento"],
    [6,"pomme","une pomme",1,"una mela"],
    [16,"pommier","un pommier",8,"un melo"],
    [7,"pompier","les pompiers",1,"i vìgili del fuoco"],
    [10,"pompier","un pompier",1,"un vìgile del fuoco"],
    [6,"porc","un porc",1,"un maiale"],
    [12,"port","un port",8,"un porto"],
    [5,"porte","une porte",1,"una porta"],
    [8,"porter","porter",1,"indossare"],
    [13,"portrait","un portrait",8,"un ritratto"],
    [16,"potager","un potager",8,"un orto"],
    [13,"poterie","une poterie",8,"una ceràmica"],
    [7,"poubelle","une poubelle",1,"un bidone"],
    [16,"poule","une poule",8,"una gallina"],
    [6,"poulet","un poulet",1,"un pollo"],
    [12,"pourboire","un pourboire",8,"una mància"],
    [16,"pousser","pousser (plante)",8,"créscere"],
    [16,"poussin","un poussin",8,"un pulcino"],
    [10,"précaire","précaire",1,"precàrio"],
    [10,"prenant","prenant",1,"impegnativo"],
    [1,"prénom","un prénom",1,"un nome"],
    [4,"préoccupé","préoccupé",1,"preoccupato"],
    [15,"présent","un présent",8,"un presente"],
    [1,"présenter","se présenter",1,"presentarsi"],
    [9,"président","un président de l'université",1,"un rettore"],
    [15,"pressé","être pressé",8,"andare di fretta"],
    [9,"primaire","être à l'école primaire",1,"fare le elementari"],
    [9,"primaire","le primaire",1,"le elementari"],
    [10,"prime","une prime",1,"un prémio"],
    [15,"printemps","le printemps",8,"la primavera"],
    [5,"prise","une prise (de courant)",1,"una presa"],
    [8,"prix","un prix",1,"un prezzo"],
    [9,"professeur","un professeur d'université",1,"un docente universitàrio"],
    [10,"professionnel","professionnel",1,"professionale"],
    [16,"profond","profond",8,"profondo"],
    [5,"profondeur","une profondeur",1,"una profondità"],
    [7,"promener","se promener",1,"passeggiare"],
    [12,"propre","propre",8,"pulito"],
    [5,"propriétaire","un propriétaire",1,"un proprietàrio"],
    [16,"protection","la protection de l'environnement",8,"la salvaguardia dell'ambiente"],
    [16,"protéger","protéger",8,"protéggere"],
    [9,"proviseur","un proviseur",1,"un préside"],
    [6,"prune","une prune",1,"una prugna"],
    [12,"public","un lieu public (bar, pub)",8,"un locale"],
    [8,"puces","les puces",1,"il mercatino delle pulci"],
    [8,"pull","un pull à col roulé",1,"un dolcevita"],
    [8,"pull","un pull",1,"un maglione/un pullover"],
    [9,"punir","punir",1,"punire"],
    [12,"quai","un quai",8,"un binàrio"],
    [1,"qualité","une qualité",1,"una qualità/una virtù"],
    [10,"qualité","les qualités requises",1,"i requisiti"],
    [7,"quartier","un quartier",1,"un quartiere"],
    [9,"question","poser des questions",1,"fare domande"],
    [7,"queue","faire la queue",1,"fare la fila"],
    [2,"quitter","se quitter",1,"lasciarsi"],
    [16,"racine","une racine",8,"una radice"],
    [5,"radiateur","un radiateur",1,"un termosifone/un radiatore"],
    [1,"radin","radin",1,"tìrchio"],
    [16,"radioactif","radioactif",8,"radioattivo"],
    [1,"raffiné","raffiné",1,"raffinato"],
    [4,"rage","une rage",1,"una ràbbia"],
    [16,"raide","raide",8,"rìpido"],
    [6,"raisin","le raisin noir",1,"l'uva nera"],
    [6,"raisin","le raisin blanc",1,"l'uva bianca"],
    [4,"rancoeur","la rancoeur",1,"il rancore"],
    [14,"randonnée","faire de la randonnée",8,"fare trekking"],
    [9,"rang","un rang",1,"una fila"],
    [6,"râpé","râpé",1,"grattuggiato"],
    [6,"râper","râper",1,"grattugiare"],
    [3,"raser","se raser la barbe",1,"farsi la barba"],
    [3,"rasoir","un rasoir",1,"un rasòio"],
    [8,"rayon","un rayon",1,"un reparto"],
    [12,"réception","une réception/un accueil",8,"una recéption"],
    [16,"réchauffement","un réchauffement",8,"un riscaldamento"],
    [6,"réchauffer","réchauffer",1,"riscaldare"],
    [16,"recyclage","un recyclage",8,"un riciclàggio"],
    [16,"recycler","recycler",8,"riciclare"],
    [9,"redoublant","un redoublant",1,"un ripetente"],
    [9,"redoubler","redoubler",1,"ripétere l'anno"],
    [11,"rééducation","un rééducation",1,"una riabilitazione"],
    [3,"regarder","regarder",1,"guardare"],
    [11,"régime","faire un régime",1,"seguire una dieta"],
    [9,"règle","une règle (école)",1,"un righello"],
    [3,"règles","les règles (menstrues)",1,"le mestruazioni"],
    [2,"remarier","se remarier",1,"risposarsi"],
    [8,"remise","une remise/une réduction",1,"uno sconto"],
    [9,"remplaçant","un remplaçant",1,"un supplente"],
    [16,"renard","un renard",8,"una volpe"],
    [5,"rénover","rénover",1,"ristrutturare"],
    [6,"repas","un repas",1,"un pasto"],
    [6,"repas","un repas de midi",1,"un pranzo"],
    [13,"répéter","répéter",8,"fare le prove"],
    [16,"requin","un requin",8,"uno squalo"],
    [12,"réservation","une réservation",8,"una prenotazione"],
    [12,"réserver","réserver",8,"prenotare"],
    [16,"résine","une résine",8,"una résina"],
    [3,"respiration","la respiration/le souffle",1,"il respiro"],
    [3,"respirer","respirer",1,"respirare"],
    [4,"ressentir","ressentir",1,"provare"],
    [16,"ressources","les ressources naturelles",8,"le risorse naturali"],
    [12,"restaurant","un restaurant",8,"un ristorante/una trattoria"],
    [15,"retard","être en retard",8,"éssere in ritardo"],
    [12,"retard","un retard",8,"un ritardo"],
    [7,"retirer","retirer de l'argent",1,"ritirare dei soldi"],
    [10,"retraite","une retraite",1,"una pensione"],
    [15,"réveiller","se réveiller",8,"svegliarsi"],
    [10,"revendication","une revendication",1,"una rivendicazione"],
    [15,"rêver","rếver (de)",8,"sognare"],
    [7,"réverbère","un réverbère",1,"un lampione"],
    [9,"réviser","réviser",1,"ripassare"],
    [5,"rez-de-chaussée","un rez-de-chaussée",1,"un pianoterra/un pianterreno"],
    [11,"rhume","un rhume",1,"un raffreddore"],
    [13,"rideau","un rideau (spectacle)",8,"un sipàrio"],
    [5,"rideau","un rideau",1,"una tenda"],
    [3,"rincer","se rincer",1,"sciacquarsi"],
    [4,"rire","rire",1,"rìdere"],
    [6,"rissoler","faire revenir/rissoler",1,"far soffrìggere/far rosolare"],
    [16,"rivage","un rivage",8,"un bagnasciuga"],
    [16,"rive","une rive",8,"una riva"],
    [6,"riz","le riz",1,"il riso"],
    [5,"robinet","un robinet",1,"un rubinetto"],
    [11,"robuste","robuste",1,"robusto"],
    [4,"rogne","se mettre en rogne (familier)",1,"incazzarsi"],
    [13,"rôle","jouer un rôle",8,"recitare una parte"],
    [13,"roman","un roman",8,"un romanzo"],
    [13,"roman","un roman policier",8,"un giallo"],
    [13,"romancier","un romancier",8,"un romanziere"],
    [6,"romarin","un romarin",1,"un rosmarino"],
    [5,"rond","rond",1,"rotondo/tondo"],
    [7,"rond-point","un rond-point",1,"una rotonda"],
    [16,"rose","une rose",8,"una rosa"],
    [12,"rosé","rosé",8,"rosato"],
    [5,"rouge","rouge",1,"rosso"],
    [3,"rouge-à-lèvres","un rouge-à-lèvres",1,"un rossetto"],
    [7,"route","une route",1,"una strada"],
    [1,"roux","roux",1,"rosso"],
    [7,"rue","une rue",1,"una via"],
    [7,"ruelle","une ruelle",1,"un vìcolo"],
    [14,"rugby","le rugby",8,"il rugby"],
    [5,"rugueux","rugueux",1,"rùvido"],
    [16,"ruisseau","un ruisseau",8,"un ruscello"],
    [16,"sable","un sable",8,"una sàbbia"],
    [12,"sac","un sac",8,"una borsa"],
    [9,"sac","un sac à dos",1,"uno zàino"],
    [12,"saignant","saignant",8,"al sàngue"],
    [11,"saigner","saigner",1,"sanguinare"],
    [15,"saison","une saison",8,"una stagione"],
    [6,"salade","une salade",1,"un'insalata"],
    [10,"salaire","un salaire",1,"uno stipéndio"],
    [10,"salarié","un salarié",1,"un dipendente"],
    [5,"sale","sale",1,"sporco"],
    [5,"salle","une salle à manger",1,"una sala da pranzo"],
    [5,"salle","une salle de bain/des toilettes",1,"un bagno"],
    [5,"salon","un salon (pièce)",1,"un salone"],
    [8,"sandale","une sandale",1,"un sandalo"],
    [12,"sandwich","un sandwich club (pain de mie)",8,"un tramezzino"],
    [12,"sandwich","un sandwich",8,"un panino"],
    [16,"sanglier","un sanglier",8,"un cinghiale"],
    [11,"santé","avoir une santé fragile",1,"éssere cagionévole di salute"],
    [11,"santé","une santé",1,"una salute"],
    [12,"saouler","se saouler",8,"ubriacarsi"],
    [16,"sapin","un sapin",8,"un abete"],
    [6,"saucisse","une saucisse",1,"una salsìccia"],
    [6,"saucisson","un saucisson",1,"un salame"],
    [6,"saumon","un saumon",1,"un salmone"],
    [3,"sauter","sauter",1,"saltare"],
    [16,"sauterelle","une sauterelle",8,"un grillo"],
    [16,"sauvage","sauvage",8,"selvàggio"],
    [3,"savon","un savon",1,"un sapone"],
    [12,"savourer","savourer",8,"assaporare"],
    [12,"savoureux","savoureux",8,"saporito"],
    [13,"saxophone","un saxophone",8,"un sassòfono"],
    [4,"scandaleux","scandaleux",1,"scandaloso"],
    [13,"scénario","un scénario",8,"una sceneggiatura"],
    [13,"scène","une scène (spectacle)",8,"uno palcoscénico"],
    [12,"scooter","un scooter",8,"un motorino/uno scooter"],
    [14,"score","un score",8,"un puntéggio"],
    [16,"scorpion","un scorpion",8,"uno scorpione"],
    [13,"sculpter","sculpter",8,"scolpire"],
    [13,"sculpteur","un sculpteur",8,"uno scultore"],
    [13,"sculpture","une sculpture",8,"una scultura"],
    [16,"sec","sec",8,"secco"],
    [16,"sécheresse","une sécheresse",8,"una siccità"],
    [5,"séchoir","un séchoir (à linge)",1,"uno stendino"],
    [15,"seconde","une seconde",8,"un secondo"],
    [10,"secrétaire","un secrétaire (travail)",1,"un segretàrio"],
    [4,"se décourager","se décourager",1,"scoraggiarsi"],
    [1,"séduisant","séduisant",1,"attraente"],
    [5,"séjour","un séjour (pièce)",1,"un soggiorno"],
    [6,"sel","le sel",1,"il sale"],
    [15,"semaine","une semaine",8,"una settimana"],
    [1,"sembler","sembler",1,"sembrare"],
    [7,"sens","un sens interdit",1,"un senso vietato"],
    [16,"sentier","un sentier",8,"un sentiero"],
    [3,"sentir","sentir (dégager une odeur)",1,"odorare"],
    [2,"séparation","une séparation",1,"una separazione"],
    [1,"séparé","séparé",1,"separato"],
    [2,"séparer","se séparer/rompre",1,"separarsi"],
    [15,"serein","serein/calme",8,"sereno"],
    [9,"sérieux","sérieux",1,"sério"],
    [16,"serpent","un serpent",8,"un serpente"],
    [16,"serre","un effet de serre",8,"un effetto serra"],
    [8,"serré","serré",1,"stretto"],
    [10,"serveur","un serveur",1,"un cameriere"],
    [1,"serviable","serviable",1,"serviziévole"],
    [6,"serviette","une serviette (de table)",1,"un tovagliolo"],
    [3,"serviette","une serviette hygiénique",1,"un assorbente"],
    [3,"serviette","une serviette",1,"un asciugamano"],
    [1,"sexe","un sexe (état civil)",1,"un sesso"],
    [3,"shampooing","un après-shampooing",1,"un bàlsamo"],
    [3,"shampooing","un shampooing",1,"uno shampoo"],
    [8,"shopping","faire du shopping",1,"fare shopping"],
    [15,"siècle","un siècle",8,"un sécolo"],
    [12,"siège","un siège",8,"un sedile"],
    [15,"sieste","faire une sieste",8,"fare un pisolino"],
    [1,"sincère","sincère",1,"sincero"],
    [11,"sirop","un sirop",1,"uno sciroppo"],
    [14,"ski","le ski",8,"lo sci"],
    [8,"slip","le slip",1,"gli slip"],
    [12,"snack","un snack",8,"una tàvola calda"],
    [2,"soeur","une soeur",1,"una sorella"],
    [11,"soigner","se soigner",1,"curarsi"],
    [15,"soir","un soir",8,"una sera"],
    [15,"soirée","une soirée",8,"una serata"],
    [5,"sol","un sol (maison)",1,"un pavimento"],
    [8,"soldes","les soldes",1,"i saldi"],
    [15,"soleil","un soleil",8,"un sole"],
    [15,"soleil","un coucher de soleil",8,"un tramonto"],
    [16,"sommet","un sommet",8,"una vetta/una cima"],
    [13,"son","une bande-son/une bande originale",8,"una colonna sonora"],
    [15,"souffler","souffler",8,"soffiare"],
    [4,"souffrir","souffrir",1,"soffrire"],
    [4,"soulagé","soulagé",1,"sollevato"],
    [4,"soulagement","un soulagement",1,"un sollievo"],
    [3,"sourcil","un sourcil, les sourcils",1,"un sopraccìglio, le sopraccìglia"],
    [4,"sourire","un sourire",1,"un sorriso"],
    [5,"sous-sol","un sous-sol (maison)",1,"un piano interrato"],
    [14,"soutenir","soutenir (une équipe)",8,"fare il tifo per/tifare"],
    [8,"soutien-gorge","un soutien-gorge",1,"un reggiseno"],
    [12,"souvenir","un souvenir (objet)",8,"un souvenir/un ricordo"],
    [12,"spacieux","spacieux",8,"spazioso"],
    [11,"spécialiste","un spécialiste",1,"uno specialista"],
    [13,"spectacle","un spectacle/une séance",8,"uno spettàcolo"],
    [14,"sport","une salle de sport/un gymnase",8,"una palestra"],
    [14,"sport","faire du sport",8,"fare sport"],
    [10,"stage","un stage",1,"un tirocìnio"],
    [10,"stagiaire","un stagiaire",1,"un stagista"],
    [12,"station","une station de métro",8,"una stazione della metro"],
    [13,"statue","une statue",8,"una stàtua"],
    [12,"steward","un steward",8,"uno steward"],
    [12,"strapontin","un strapontin",8,"uno strapuntino"],
    [8,"string","un string",1,"un perizoma"],
    [13,"strophe","une strophe",8,"una strofa"],
    [9,"studieux","studieux",1,"studioso"],
    [4,"stupeur","une stupeur",1,"uno stupore"],
    [9,"stylo","un stylo",1,"una penna"],
    [8,"supermarché","un supermarché",1,"un supermercato"],
    [14,"supporter","un supporter",8,"un tifoso"],
    [6,"surcre","le sucre",1,"il zùcchero"],
    [1,"surnom","un surnom",1,"un nomignolo/un soprannome"],
    [4,"surprenant","surprenant",1,"stupefacente"],
    [4,"surprise","une surprise",1,"una sorpresa"],
    [8,"survêtement","un survêtement",1,"una tuta"],
    [1,"susceptible","susceptible",1,"permaloso"],
    [8,"sweat-shirt","un sweat-shirt",1,"una felpa"],
    [1,"sympathique","sympatique",1,"simpàtico"],
    [11,"symptôme","un symptôme",1,"un sìntomo"],
    [10,"syndicaliste","un syndicaliste",1,"un sindacalista"],
    [10,"syndicat","un syndicat",1,"un sindacato"],
    [5,"table","une table de chevet",1,"un comodino"],
    [5,"table","une table",1,"un tàvolo"],
    [9,"tableau","un tableau",1,"una lavagna"],
    [1,"taciturne","taciturne",1,"taciturno"],
    [5,"taie","la taie",1,"la fédera"],
    [3,"taille","une taille (partie du corps)",1,"una vita"],
    [1,"taille","une taille (aspect physique)",1,"un'altezza"],
    [8,"talon","un talon",1,"un tacco"],
    [3,"tampon","un tampon hygiénique",1,"un assorbente interno"],
    [2,"tante","une tante",1,"una zia"],
    [5,"tapis","un tapis",1,"un tappeto"],
    [6,"tasse","une tasse",1,"una tazza"],
    [13,"télé","regarder la télé",8,"guardare la tivù"],
    [1,"tempérament","un tempérament",1,"un'ìndole"],
    [15,"tempête","une tempête",8,"una tempesta"],
    [10,"temps","un temps partiel",1,"un part time"],
    [9,"temps","un emploi du temps",1,"un oràrio"],
    [15,"temps","un temps",8,"un tempo"],
    [10,"temps","un temps complet",1,"un tempo pieno"],
    [4,"tendresse","une tendresse",1,"una tenerezza"],
    [14,"tennis","un tennis",8,"un tennis"],
    [12,"tente","une tente",8,"una tenda"],
    [12,"terminus","un terminus",8,"un capolìnea"],
    [5,"terne","terne",1,"spento"],
    [14,"terrain","un terrain/un court",8,"un campo"],
    [16,"terre","une terre",8,"una terra"],
    [4,"terrifiant","terrifiant",1,"terrificante"],
    [3,"tête","une tête",1,"una testa"],
    [11,"tête","un mal de tête",1,"un mal di testa"],
    [11,"thérapie","une thérapie",1,"una terapia"],
    [9,"thèse","une thèse",1,"una tesi di dottorato"],
    [6,"thon","un thon",1,"un tonno"],
    [6,"thym","un thym",1,"un timo"],
    [8,"ticket","un ticket de caisse",1,"uno scontrino"],
    [6,"tiède","tiède",1,"tiépido"],
    [16,"tige","une tige",8,"un gambo/uno stelo"],
    [1,"timide","timide",1,"tìmido"],
    [6,"tire-bouchon","un tire-bouchon",1,"un cavatappi"],
    [5,"tiroir","un tiroir",1,"un cassetto"],
    [13,"titres","les sous-titres",8,"i sottotìtoli"],
    [5,"toit","un toit",1,"un tetto"],
    [6,"tomate","une tomate",1,"un pomodoro"],
    [11,"tomber","tomber malade",1,"ammalarsi"],
    [4,"tomber","tomber amoureux",1,"innamorarsi"],
    [15,"tonnerre","un tonnerre",8,"un tuòno"],
    [6,"torchon","un torchon",1,"uno strofinàccio/uno stràccio"],
    [16,"torrent","un torrent",8,"un torrente"],
    [3,"toucher","toucher",1,"toccare"],
    [3,"toucher","un toucher",1,"un tatto"],
    [16,"touffu","touffu",8,"folto"],
    [16,"tournesol","un tournesol",8,"un girasole"],
    [14,"tournoi","un tournoi",8,"un tornéo"],
    [11,"tousser","tousser",1,"tossire"],
    [12,"train","un train",8,"un treno"],
    [12,"tramway","un tramway",8,"un tram"],
    [16,"transgénique","transgénique",8,"transgénico"],
    [3,"transpiration","la transpiration",1,"il sudore"],
    [1,"trapu","trapu",1,"tozzo/tarchiato"],
    [10,"travailler","travailler",1,"lavorare"],
    [10,"travailleur","un travailleur indépendant",1,"un lìbero professionista"],
    [16,"tri","le tri sélectif des déchets",8,"la raccolta differenziata"],
    [5,"triangulaire","triangulaire",1,"triangolare"],
    [8,"tricot","un tricot",1,"un màglia"],
    [13,"tricoter","tricoter",8,"lavorare a màglia"],
    [12,"trinquer","trinquer",8,"brindare/fare un brìndisi"],
    [4,"tristesse","une tristesse",1,"una tristezza"],
    [13,"trompette","une trompette",8,"una tromba"],
    [16,"tronc","un tronc",8,"un tronco"],
    [7,"trottoir","un trottoir",1,"un marciapiede"],
    [9,"trousse","une trousse",1,"un astùccio"],
    [16,"truite","une truite",8,"una trota"],
    [8,"t-shirt","un t-shirt",1,"una maglietta/una t-shirt"],
    [16,"tulipe","une tulipe",8,"un tulipano"],
    [2,"tutelle","en tutelle",1,"in affidamento"],
    [2,"union","l'union libre",1,"la còppia di fatto"],
    [7,"urgence","les urgences",1,"il pronto soccorso"],
    [10,"usine","une usine",1,"una fàbbrica"],
    [6,"ustensile","les ustensiles",1,"gli uténsili"],
    [11,"vaccin","un vaccin",1,"un vaccino"],
    [6,"vache","de vache",1,"di mucca/vaccino"],
    [16,"vache","une vache",8,"una vacca"],
    [16,"vache","une vache (laitière)",8,"una mucca"],
    [16,"vague","une vague",8,"un'onda"],
    [12,"valise","une valise",8,"una valìgia"],
    [1,"vaniteux","vaniteux",1,"vanitoso"],
    [12,"vapeur","à la vapeur",8,"al vapore"],
    [6,"veau","un veau",1,"un vitello"],
    [12,"végétarien","végétarien",8,"vegetariano"],
    [12,"vélo","un vélo",8,"una bici"],
    [14,"vélo","faire du vélo",8,"andare in bici"],
    [8,"vendeur","un vendeur",1,"un commesso"],
    [15,"vent","un vent",8,"un vento"],
    [3,"ventre","un ventre",1,"una pància"],
    [3,"vernis","un vernis à ongles",1,"uno smalto"],
    [5,"verre","le verre (matière)",1,"il vetro"],
    [6,"verre","un verre (pour boire)",1,"un bicchiere"],
    [13,"vers","écrire des vers",8,"comporre dei versi"],
    [13,"vers","un vers (littérature)",8,"un verso"],
    [6,"vert","vert (pas mûr)",1,"acerbo"],
    [5,"vert","vert",1,"verde"],
    [8,"veste","une veste",1,"una giacca"],
    [1,"veuf","veuf",1,"védovo"],
    [6,"viande","une viande",1,"una carne"],
    [2,"vieillesse","une vieillesse",1,"una vecchiàia"],
    [2,"vieillir","vieillir",1,"invecchiare"],
    [1,"vieux","vieux",1,"vécchio"],
    [15,"vieux","vieux jeu",8,"vécchio stile"],
    [5,"vif","vif (couleur)",1,"acceso"],
    [16,"vigne","une vigne",8,"una vite"],
    [5,"villa","la villa",1,"la villa"],
    [12,"vin","un vin",8,"un vino"],
    [6,"vinaigre","un vinaigre",1,"un aceto"],
    [16,"violette","une violette",8,"una viola"],
    [13,"violon","un violon",8,"un violino"],
    [12,"visa","un visa",8,"un visto"],
    [3,"visage","un visage",1,"un viso"],
    [5,"visiter","visiter",1,"visitare"],
    [2,"vivre","vivre ensemble",1,"convìvere"],
    [3,"voir","voir",1,"vedere"],
    [12,"voiture","une voiture",8,"una màcchina"],
    [14,"volley-ball","le volley-ball",8,"la pallavolo"],
    [11,"vomir","vomir",1,"vomitare"],
    [12,"voyage","un voyage organisé",8,"un viàggio organizzato"],
    [3,"vue","la vue",1,"la vista"],
    [1,"vulgaire","vulgaire",1,"volgare"],
    [12,"wagon","un wagon",8,"un vagone/una carrozza"],
    [14,"water-polo","le water-polo",8,"la pallanuoto"],
    [7,"zone","une zone piétonne",1,"un'àrea pedonale"]]

liste.each do |m|
  @m = Mot.find_by(francais: m[2])
  if @m
    @m.category_id = m[0]
    @m.mot_directeur = m[1]
    @m.italien = m[4]
    @m.save!
    User.all.each do |u|
      sc = u.scores_mots.find_by(mot_id: @m.id)
      sc.category_id = m[0]
      sc.save!
    end
  else
    @m = Mot.create(category_id: m[0], mot_directeur: m[1], francais: m[2], italien: m[4])
    User.all.each do |u|
      u.scores_mots.create(mot_id: @m.id, category_id: m[0], compteur: m[3])
    end
  end
end

liste = [
    ["amare",
     [[0, "amo",8],
      [1, "ami",8],
      [2, "ama",8],
      [3, "amiamo",8],
      [4, "amate",8],
      [5, "àmano",8],
      [6, "amavo",8],
      [7, "amavi",8],
      [8, "amava",8],
      [9, "amavamo",8],
      [10, "amavate",8],
      [11, "amàvano",8],
      [12, "amai",1],
      [13, "amasti",1],
      [14, "amò",1],
      [15, "amammo",1],
      [16, "amaste",1],
      [17, "amàrono",1],
      [18, "amerò",8],
      [19, "amerai",8],
      [20, "amerà",8],
      [21, "ameremo",8],
      [22, "amerete",8],
      [23, "ameranno",8],
      [24, "ami",8],
      [25, "ami",8],
      [26, "ami",8],
      [27, "amiamo",8],
      [28, "amiate",8],
      [29, "àmino",8],
      [30, "amassi",2],
      [31, "amassi",2],
      [32, "amasse",2],
      [33, "amàssimo",2],
      [34, "amaste",2],
      [35, "amàssero",2],
      [36, "",0],
      [37, "ama",8],
      [38, "ami",8],
      [39, "amiamo",8],
      [40, "amate",8],
      [41, "àmino",8],
      [42, "amerei",8],
      [43, "ameresti",8],
      [44, "amerebbe",8],
      [45, "ameremmo",8],
      [46, "amereste",8],
      [47, "amerébbero",8],
      [48, "amando",8],
      [49, "amato",8]]],
    ["avere",
     [[0, "ho",8],
      [1, "hai",8],
      [2, "ha",8],
      [3, "abbiamo",8],
      [4, "avete",8],
      [5, "hanno",8],
      [6, "avevo",8],
      [7, "avevi",8],
      [8, "aveva",8],
      [9, "avevamo",8],
      [10, "avevate",8],
      [11, "avévano",8],
      [12, "ebbi",1],
      [13, "avesti",1],
      [14, "ebbe",1],
      [15, "avemmo",1],
      [16, "aveste",1],
      [17, "ébbero",1],
      [18, "avrò",8],
      [19, "avrai",8],
      [20, "avrà",8],
      [21, "avremo",8],
      [22, "avrete",8],
      [23, "avranno",8],
      [24, "àbbia",8],
      [25, "àbbia",8],
      [26, "àbbia",8],
      [27, "abbiamo",8],
      [28, "abbiate",8],
      [29, "àbbiano",8],
      [30, "avessi",2],
      [31, "avessi",2],
      [32, "avesse",2],
      [33, "avéssimo",2],
      [34, "aveste",2],
      [35, "avéssero",2],
      [36, "",0],
      [37, "abbi",8],
      [38, "àbbia",8],
      [39, "abbiamo",8],
      [40, "abbiate",8],
      [41, "àbbiano",8],
      [42, "avrei",8],
      [43, "avresti",8],
      [44, "avrebbe",8],
      [45, "avremmo",8],
      [46, "avreste",8],
      [47, "avrébbero",8],
      [48, "avento",8],
      [49, "avuto",8]]],
    ["crédere",
     [[0, "credo",8],
      [1, "credi",8],
      [2, "crede",8],
      [3, "crediamo",8],
      [4, "credete",8],
      [5, "crédono",8],
      [6, "credevo",8],
      [7, "credevi",8],
      [8, "credeva",8],
      [9, "credevamo",8],
      [10, "credevate",8],
      [11, "credévano",8],
      [12, "credei/credetti",1],
      [13, "credesti",1],
      [14, "credé/credette",1],
      [15, "credemmo",1],
      [16, "credeste",1],
      [17, "credérono/credéttero",1],
      [18, "crederò",8],
      [19, "crederai",8],
      [20, "crederà",8],
      [21, "crederemo",8],
      [22, "crederete",8],
      [23, "crederanno",8],
      [24, "creda",8],
      [25, "creda",8],
      [26, "creda",8],
      [27, "crediamo",8],
      [28, "crediate",8],
      [29, "crédano",8],
      [30, "credessi",2],
      [31, "credessi",2],
      [32, "credesse",2],
      [33, "credéssimo",2],
      [34, "credeste",2],
      [35, "credéssero",2],
      [36, "",0],
      [37, "credi",8],
      [38, "creda",8],
      [39, "crediamo",8],
      [40, "credete",8],
      [41, "crédano",8],
      [42, "crederei",8],
      [43, "crederesti",8],
      [44, "crederebbe",8],
      [45, "crederemmo",8],
      [46, "credereste",8],
      [47, "crederébbero",8],
      [48, "credendo",8],
      [49, "creduto",8]]],
    ["dormire",
     [[0, "dormo",8],
      [1, "dormi",8],
      [2, "dorme",8],
      [3, "dormiamo",8],
      [4, "dormite",8],
      [5, "dòrmono",8],
      [6, "dormivo",8],
      [7, "dormivi",8],
      [8, "dormiva",8],
      [9, "dormivamo",8],
      [10, "dormivate",8],
      [11, "dormìvano",8],
      [12, "dormii",1],
      [13, "dormisti",1],
      [14, "dormì",1],
      [15, "dormimmo",1],
      [16, "dormiste",1],
      [17, "dormìrono",1],
      [18, "dormirò",8],
      [19, "dormirai",8],
      [20, "dormirà",8],
      [21, "dormiremo",8],
      [22, "dormirete",8],
      [23, "dormiranno",8],
      [24, "dorma",8],
      [25, "dorma",8],
      [26, "dorma",8],
      [27, "dormiamo",8],
      [28, "dormiate",8],
      [29, "dòrmano",8],
      [30, "dormissi",2],
      [31, "dormissi",2],
      [32, "dormisse",2],
      [33, "dormìssimo",2],
      [34, "dormiste",2],
      [35, "dormìssero",2],
      [36, "",0],
      [37, "dormi",8],
      [38, "dorma",8],
      [39, "dormiamo",8],
      [40, "dormite",8],
      [41, "dòrmano",8],
      [42, "dormirei",8],
      [43, "dormiresti",8],
      [44, "dormirebbe",8],
      [45, "dormiremmo",8],
      [46, "dormireste",8],
      [47, "dormirébbero",8],
      [48, "dormendo",8],
      [49, "dormito",8]]],
    ["éssere",
     [[0, "sono",8],
      [1, "sei",8],
      [2, "è",8],
      [3, "siamo",8],
      [4, "siete",8],
      [5, "sono",8],
      [6, "ero",8],
      [7, "eri",8],
      [8, "era",8],
      [9, "eravamo",8],
      [10, "eravate",8],
      [11, "érano",8],
      [12, "fui",1],
      [13, "fosti",1],
      [14, "fu",1],
      [15, "fummo",1],
      [16, "foste",1],
      [17, "fùrono",1],
      [18, "sarò",8],
      [19, "sarai",8],
      [20, "sarà",8],
      [21, "saremo",8],
      [22, "sarete",8],
      [23, "saranno",8],
      [24, "sia",8],
      [25, "sia",8],
      [26, "sia",8],
      [27, "siamo",8],
      [28, "siate",8],
      [29, "sìano",8],
      [30, "fossi",2],
      [31, "fossi",2],
      [32, "fosse",2],
      [33, "fòssimo",2],
      [34, "foste",2],
      [35, "fòssero",2],
      [36, "",0],
      [37, "sii",8],
      [38, "sia",8],
      [39, "siamo",8],
      [40, "siate",8],
      [41, "sìano",8],
      [42, "sarei",8],
      [43, "saresti",8],
      [44, "sarebbe",8],
      [45, "saremmo",8],
      [46, "sareste",8],
      [47, "sarébbero",8],
      [48, "essendo",8],
      [49, "stato",8]]],
    ["vedere",
     [[0, "vedo",8],
      [1, "vedi",8],
      [2, "vede",8],
      [3, "vediamo",8],
      [4, "vedete",8],
      [5, "védono",8],
      [6, "vedevo",8],
      [7, "vedevi",8],
      [8, "vedeva",8],
      [9, "vedevamo",8],
      [10, "vedevate",8],
      [11, "vedévano",8],
      [12, "vidi",1],
      [13, "vedesti",1],
      [14, "vide",1],
      [15, "vedemmo",1],
      [16, "vedeste",1],
      [17, "vìdero",1],
      [18, "vedrò",8],
      [19, "vedrai",8],
      [20, "vedrà",8],
      [21, "vedremo",8],
      [22, "vedrete",8],
      [23, "vedranno",8],
      [24, "veda",8],
      [25, "veda",8],
      [26, "veda",8],
      [27, "vediamo",8],
      [28, "vediate",8],
      [29, "védano",8],
      [30, "vedessi",2],
      [31, "vedessi",2],
      [32, "vedesse",2],
      [33, "vedéssimo",2],
      [34, "vedeste",2],
      [35, "vedéssero",2],
      [36, "",0],
      [37, "vedi",8],
      [38, "veda",8],
      [39, "vediamo",8],
      [40, "vedete",8],
      [41, "védano",8],
      [42, "vedrei",8],
      [43, "vedresti",8],
      [44, "vedrebbe",8],
      [45, "vedremmo",8],
      [46, "vedreste",8],
      [47, "vedrébbero",8],
      [48, "vedendo",8],
      [49, "visto/veduto",8]]]]

liste.each do |verbe|
  @verbe = Verbe.find_by(infinitif: verbe[0])
  unless @verbe
    @verbe = Verbe.create(infinitif: verbe[0])
  end
  verbe[1].each do |forme|
    @forme = @verbe.formes.find_by(rang_forme: forme[0])
    if @forme
      @forme.italien = forme[1]
      @forme.save!
      User.all.each do |user|
        sf = user.scores_formes.find_by(forme_id: @forme.id)
        sf.rang_forme = forme[0]
        sf.save!
      end
    else
      @forme = @verbe.formes.create(rang_forme: forme[0], italien: forme[1])
      User.all.each do |user|
        user.scores_formes.create(rang_forme: forme[0], forme_id: @forme.id, compteur: forme[2])
      end
    end
  end
end